# AUTOGENERATED: DO NOT EDIT
# Last update date: 2025-04-21 00:01:54.144002

from ctypes import *


NVC9C0_QMDV02_04_RUN_CTA_IN_ONE_SM_PARTITION_FALSE: int = 0x0
NVC9C0_QMDV02_04_RUN_CTA_IN_ONE_SM_PARTITION_TRUE: int = 0x1
NVC9C0_QMDV02_04_IS_QUEUE_FALSE: int = 0x0
NVC9C0_QMDV02_04_IS_QUEUE_TRUE: int = 0x1
NVC9C0_QMDV02_04_ADD_TO_HEAD_OF_QMD_GROUP_LINKED_LIST_FALSE: int = 0x0
NVC9C0_QMDV02_04_ADD_TO_HEAD_OF_QMD_GROUP_LINKED_LIST_TRUE: int = 0x1
NVC9C0_QMDV02_04_SEMAPHORE_RELEASE_ENABLE0_FALSE: int = 0x0
NVC9C0_QMDV02_04_SEMAPHORE_RELEASE_ENABLE0_TRUE: int = 0x1
NVC9C0_QMDV02_04_SEMAPHORE_RELEASE_ENABLE1_FALSE: int = 0x0
NVC9C0_QMDV02_04_SEMAPHORE_RELEASE_ENABLE1_TRUE: int = 0x1
NVC9C0_QMDV02_04_REQUIRE_SCHEDULING_PCAS_FALSE: int = 0x0
NVC9C0_QMDV02_04_REQUIRE_SCHEDULING_PCAS_TRUE: int = 0x1
NVC9C0_QMDV02_04_DEPENDENT_QMD0_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV02_04_DEPENDENT_QMD0_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV02_04_DEPENDENT_QMD0_ACTION_QMD_INCREMENT_PUT: int = 0x0
NVC9C0_QMDV02_04_DEPENDENT_QMD0_ACTION_QMD_SCHEDULE: int = 0x1
NVC9C0_QMDV02_04_DEPENDENT_QMD0_ACTION_QMD_INVALIDATE_COPY_SCHEDULE: int = 0x3
NVC9C0_QMDV02_04_DEPENDENT_QMD0_ACTION_QMD_DECREMENT_DEPENDENCE: int = 0x4
NVC9C0_QMDV02_04_DEPENDENT_QMD0_PREFETCH_FALSE: int = 0x0
NVC9C0_QMDV02_04_DEPENDENT_QMD0_PREFETCH_TRUE: int = 0x1
NVC9C0_QMDV02_04_DEPENDENT_QMD1_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV02_04_DEPENDENT_QMD1_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV02_04_DEPENDENT_QMD1_ACTION_QMD_INCREMENT_PUT: int = 0x0
NVC9C0_QMDV02_04_DEPENDENT_QMD1_ACTION_QMD_SCHEDULE: int = 0x1
NVC9C0_QMDV02_04_DEPENDENT_QMD1_ACTION_QMD_INVALIDATE_COPY_SCHEDULE: int = 0x3
NVC9C0_QMDV02_04_DEPENDENT_QMD1_ACTION_QMD_DECREMENT_DEPENDENCE: int = 0x4
NVC9C0_QMDV02_04_DEPENDENT_QMD1_PREFETCH_FALSE: int = 0x0
NVC9C0_QMDV02_04_DEPENDENT_QMD1_PREFETCH_TRUE: int = 0x1
NVC9C0_QMDV02_04_SELF_COPY_ON_COMPLETION_FALSE: int = 0x0
NVC9C0_QMDV02_04_SELF_COPY_ON_COMPLETION_TRUE: int = 0x1
NVC9C0_QMDV02_04_INVALIDATE_TEXTURE_HEADER_CACHE_FALSE: int = 0x0
NVC9C0_QMDV02_04_INVALIDATE_TEXTURE_HEADER_CACHE_TRUE: int = 0x1
NVC9C0_QMDV02_04_INVALIDATE_TEXTURE_SAMPLER_CACHE_FALSE: int = 0x0
NVC9C0_QMDV02_04_INVALIDATE_TEXTURE_SAMPLER_CACHE_TRUE: int = 0x1
NVC9C0_QMDV02_04_INVALIDATE_TEXTURE_DATA_CACHE_FALSE: int = 0x0
NVC9C0_QMDV02_04_INVALIDATE_TEXTURE_DATA_CACHE_TRUE: int = 0x1
NVC9C0_QMDV02_04_INVALIDATE_SHADER_DATA_CACHE_FALSE: int = 0x0
NVC9C0_QMDV02_04_INVALIDATE_SHADER_DATA_CACHE_TRUE: int = 0x1
NVC9C0_QMDV02_04_INVALIDATE_INSTRUCTION_CACHE_FALSE: int = 0x0
NVC9C0_QMDV02_04_INVALIDATE_INSTRUCTION_CACHE_TRUE: int = 0x1
NVC9C0_QMDV02_04_INVALIDATE_SHADER_CONSTANT_CACHE_FALSE: int = 0x0
NVC9C0_QMDV02_04_INVALIDATE_SHADER_CONSTANT_CACHE_TRUE: int = 0x1
NVC9C0_QMDV02_04_RELEASE_MEMBAR_TYPE_FE_NONE: int = 0x0
NVC9C0_QMDV02_04_RELEASE_MEMBAR_TYPE_FE_SYSMEMBAR: int = 0x1
NVC9C0_QMDV02_04_CWD_REFERENCE_COUNT_INCR_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV02_04_CWD_REFERENCE_COUNT_INCR_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV02_04_CWD_MEMBAR_TYPE_L1_NONE: int = 0x0
NVC9C0_QMDV02_04_CWD_MEMBAR_TYPE_L1_SYSMEMBAR: int = 0x1
NVC9C0_QMDV02_04_CWD_MEMBAR_TYPE_L1_MEMBAR: int = 0x3
NVC9C0_QMDV02_04_SEQUENTIALLY_RUN_CTAS_FALSE: int = 0x0
NVC9C0_QMDV02_04_SEQUENTIALLY_RUN_CTAS_TRUE: int = 0x1
NVC9C0_QMDV02_04_CWD_REFERENCE_COUNT_DECR_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV02_04_CWD_REFERENCE_COUNT_DECR_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV02_04_API_VISIBLE_CALL_LIMIT__32: int = 0x0
NVC9C0_QMDV02_04_API_VISIBLE_CALL_LIMIT_NO_CHECK: int = 0x1
NVC9C0_QMDV02_04_SAMPLER_INDEX_INDEPENDENTLY: int = 0x0
NVC9C0_QMDV02_04_SAMPLER_INDEX_VIA_HEADER_INDEX: int = 0x1
NVC9C0_QMDV02_04_DISABLE_AUTO_INVALIDATE_FALSE: int = 0x0
NVC9C0_QMDV02_04_DISABLE_AUTO_INVALIDATE_TRUE: int = 0x1
NVC9C0_QMDV02_04_CONSTANT_BUFFER_VALID_FALSE: int = 0x0
NVC9C0_QMDV02_04_CONSTANT_BUFFER_VALID_TRUE: int = 0x1
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_OP_RED_ADD: int = 0x0
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_OP_RED_MIN: int = 0x1
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_OP_RED_MAX: int = 0x2
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_OP_RED_INC: int = 0x3
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_OP_RED_DEC: int = 0x4
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_OP_RED_AND: int = 0x5
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_OP_RED_OR: int = 0x6
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_OP_RED_XOR: int = 0x7
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_FORMAT_UNSIGNED_32: int = 0x0
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_FORMAT_SIGNED_32: int = 0x1
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV02_04_RELEASE0_REDUCTION_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV02_04_RELEASE0_STRUCTURE_SIZE_FOUR_WORDS: int = 0x0
NVC9C0_QMDV02_04_RELEASE0_STRUCTURE_SIZE_ONE_WORD: int = 0x1
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_OP_RED_ADD: int = 0x0
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_OP_RED_MIN: int = 0x1
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_OP_RED_MAX: int = 0x2
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_OP_RED_INC: int = 0x3
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_OP_RED_DEC: int = 0x4
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_OP_RED_AND: int = 0x5
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_OP_RED_OR: int = 0x6
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_OP_RED_XOR: int = 0x7
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_FORMAT_UNSIGNED_32: int = 0x0
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_FORMAT_SIGNED_32: int = 0x1
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV02_04_RELEASE1_REDUCTION_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV02_04_RELEASE1_STRUCTURE_SIZE_FOUR_WORDS: int = 0x0
NVC9C0_QMDV02_04_RELEASE1_STRUCTURE_SIZE_ONE_WORD: int = 0x1
NVC9C0_QMDV02_04_PROGRAM_PREFETCH_TYPE_PREFETCH_LAUNCH: int = 0x0
NVC9C0_QMDV02_04_PROGRAM_PREFETCH_TYPE_PREFTECH_POST: int = 0x1
NVC9C0_QMDV02_04_CONSTANT_BUFFER_PREFETCH_POST_FALSE: int = 0x0
NVC9C0_QMDV02_04_CONSTANT_BUFFER_PREFETCH_POST_TRUE: int = 0x1
NVC9C0_QMDV02_04_CONSTANT_BUFFER_INVALIDATE_FALSE: int = 0x0
NVC9C0_QMDV02_04_CONSTANT_BUFFER_INVALIDATE_TRUE: int = 0x1
NVC9C0_QMDV02_04_HW_ONLY_SPAN_LIST_HEAD_INDEX_VALID_FALSE: int = 0x0
NVC9C0_QMDV02_04_HW_ONLY_SPAN_LIST_HEAD_INDEX_VALID_TRUE: int = 0x1
NVC9C0_QMDV03_00_RUN_CTA_IN_ONE_SM_PARTITION_FALSE: int = 0x0
NVC9C0_QMDV03_00_RUN_CTA_IN_ONE_SM_PARTITION_TRUE: int = 0x1
NVC9C0_QMDV03_00_IS_QUEUE_FALSE: int = 0x0
NVC9C0_QMDV03_00_IS_QUEUE_TRUE: int = 0x1
NVC9C0_QMDV03_00_ADD_TO_HEAD_OF_QMD_GROUP_LINKED_LIST_FALSE: int = 0x0
NVC9C0_QMDV03_00_ADD_TO_HEAD_OF_QMD_GROUP_LINKED_LIST_TRUE: int = 0x1
NVC9C0_QMDV03_00_REQUIRE_SCHEDULING_PCAS_FALSE: int = 0x0
NVC9C0_QMDV03_00_REQUIRE_SCHEDULING_PCAS_TRUE: int = 0x1
NVC9C0_QMDV03_00_SELF_COPY_ON_COMPLETION_FALSE: int = 0x0
NVC9C0_QMDV03_00_SELF_COPY_ON_COMPLETION_TRUE: int = 0x1
NVC9C0_QMDV03_00_INVALIDATE_TEXTURE_HEADER_CACHE_FALSE: int = 0x0
NVC9C0_QMDV03_00_INVALIDATE_TEXTURE_HEADER_CACHE_TRUE: int = 0x1
NVC9C0_QMDV03_00_INVALIDATE_TEXTURE_SAMPLER_CACHE_FALSE: int = 0x0
NVC9C0_QMDV03_00_INVALIDATE_TEXTURE_SAMPLER_CACHE_TRUE: int = 0x1
NVC9C0_QMDV03_00_INVALIDATE_TEXTURE_DATA_CACHE_FALSE: int = 0x0
NVC9C0_QMDV03_00_INVALIDATE_TEXTURE_DATA_CACHE_TRUE: int = 0x1
NVC9C0_QMDV03_00_INVALIDATE_SHADER_DATA_CACHE_FALSE: int = 0x0
NVC9C0_QMDV03_00_INVALIDATE_SHADER_DATA_CACHE_TRUE: int = 0x1
NVC9C0_QMDV03_00_INVALIDATE_INSTRUCTION_CACHE_FALSE: int = 0x0
NVC9C0_QMDV03_00_INVALIDATE_INSTRUCTION_CACHE_TRUE: int = 0x1
NVC9C0_QMDV03_00_INVALIDATE_SHADER_CONSTANT_CACHE_FALSE: int = 0x0
NVC9C0_QMDV03_00_INVALIDATE_SHADER_CONSTANT_CACHE_TRUE: int = 0x1
NVC9C0_QMDV03_00_CWD_REFERENCE_COUNT_INCR_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_CWD_REFERENCE_COUNT_INCR_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_CWD_MEMBAR_TYPE_L1_NONE: int = 0x0
NVC9C0_QMDV03_00_CWD_MEMBAR_TYPE_L1_SYSMEMBAR: int = 0x1
NVC9C0_QMDV03_00_CWD_MEMBAR_TYPE_L1_MEMBAR: int = 0x3
NVC9C0_QMDV03_00_SEQUENTIALLY_RUN_CTAS_FALSE: int = 0x0
NVC9C0_QMDV03_00_SEQUENTIALLY_RUN_CTAS_TRUE: int = 0x1
NVC9C0_QMDV03_00_CWD_REFERENCE_COUNT_DECR_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_CWD_REFERENCE_COUNT_DECR_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_API_VISIBLE_CALL_LIMIT__32: int = 0x0
NVC9C0_QMDV03_00_API_VISIBLE_CALL_LIMIT_NO_CHECK: int = 0x1
NVC9C0_QMDV03_00_SAMPLER_INDEX_INDEPENDENTLY: int = 0x0
NVC9C0_QMDV03_00_SAMPLER_INDEX_VIA_HEADER_INDEX: int = 0x1
NVC9C0_QMDV03_00_DISABLE_AUTO_INVALIDATE_FALSE: int = 0x0
NVC9C0_QMDV03_00_DISABLE_AUTO_INVALIDATE_TRUE: int = 0x1
NVC9C0_QMDV03_00_DEPENDENT_QMD0_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_DEPENDENT_QMD0_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_DEPENDENT_QMD0_ACTION_QMD_INCREMENT_PUT: int = 0x0
NVC9C0_QMDV03_00_DEPENDENT_QMD0_ACTION_QMD_SCHEDULE: int = 0x1
NVC9C0_QMDV03_00_DEPENDENT_QMD0_ACTION_QMD_INVALIDATE_COPY_SCHEDULE: int = 0x3
NVC9C0_QMDV03_00_DEPENDENT_QMD0_ACTION_QMD_DECREMENT_DEPENDENCE: int = 0x4
NVC9C0_QMDV03_00_DEPENDENT_QMD0_PREFETCH_FALSE: int = 0x0
NVC9C0_QMDV03_00_DEPENDENT_QMD0_PREFETCH_TRUE: int = 0x1
NVC9C0_QMDV03_00_DEPENDENT_QMD1_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_DEPENDENT_QMD1_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_DEPENDENT_QMD1_ACTION_QMD_INCREMENT_PUT: int = 0x0
NVC9C0_QMDV03_00_DEPENDENT_QMD1_ACTION_QMD_SCHEDULE: int = 0x1
NVC9C0_QMDV03_00_DEPENDENT_QMD1_ACTION_QMD_INVALIDATE_COPY_SCHEDULE: int = 0x3
NVC9C0_QMDV03_00_DEPENDENT_QMD1_ACTION_QMD_DECREMENT_DEPENDENCE: int = 0x4
NVC9C0_QMDV03_00_DEPENDENT_QMD1_PREFETCH_FALSE: int = 0x0
NVC9C0_QMDV03_00_DEPENDENT_QMD1_PREFETCH_TRUE: int = 0x1
NVC9C0_QMDV03_00_CONSTANT_BUFFER_VALID_FALSE: int = 0x0
NVC9C0_QMDV03_00_CONSTANT_BUFFER_VALID_TRUE: int = 0x1
NVC9C0_QMDV03_00_SHARED_ALLOCATION_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_SHARED_ALLOCATION_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_MEMBAR_TYPE_FE_NONE: int = 0x0
NVC9C0_QMDV03_00_RELEASE0_MEMBAR_TYPE_FE_SYSMEMBAR: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_OP_RED_ADD: int = 0x0
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_OP_RED_MIN: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_OP_RED_MAX: int = 0x2
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_OP_RED_INC: int = 0x3
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_OP_RED_DEC: int = 0x4
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_OP_RED_AND: int = 0x5
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_OP_RED_OR: int = 0x6
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_OP_RED_XOR: int = 0x7
NVC9C0_QMDV03_00_RELEASE0_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE0_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_FORMAT_UNSIGNED: int = 0x0
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_FORMAT_SIGNED: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE0_REDUCTION_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_TRAP_TYPE_TRAP_NONE: int = 0x0
NVC9C0_QMDV03_00_RELEASE0_TRAP_TYPE_TRAP_UNCONDITIONAL: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_TRAP_TYPE_TRAP_CONDITIONAL: int = 0x2
NVC9C0_QMDV03_00_RELEASE0_TRAP_TYPE_TRAP_CONDITIONAL_EXT: int = 0x3
NVC9C0_QMDV03_00_RELEASE0_PAYLOAD64B_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE0_PAYLOAD64B_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_STRUCTURE_SIZE_SEMAPHORE_FOUR_WORDS: int = 0x0
NVC9C0_QMDV03_00_RELEASE0_STRUCTURE_SIZE_SEMAPHORE_ONE_WORD: int = 0x1
NVC9C0_QMDV03_00_RELEASE0_STRUCTURE_SIZE_SEMAPHORE_TWO_WORDS: int = 0x2
NVC9C0_QMDV03_00_RELEASE1_MEMBAR_TYPE_FE_NONE: int = 0x0
NVC9C0_QMDV03_00_RELEASE1_MEMBAR_TYPE_FE_SYSMEMBAR: int = 0x1
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_OP_RED_ADD: int = 0x0
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_OP_RED_MIN: int = 0x1
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_OP_RED_MAX: int = 0x2
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_OP_RED_INC: int = 0x3
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_OP_RED_DEC: int = 0x4
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_OP_RED_AND: int = 0x5
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_OP_RED_OR: int = 0x6
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_OP_RED_XOR: int = 0x7
NVC9C0_QMDV03_00_RELEASE1_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE1_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_FORMAT_UNSIGNED: int = 0x0
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_FORMAT_SIGNED: int = 0x1
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE1_REDUCTION_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE1_TRAP_TYPE_TRAP_NONE: int = 0x0
NVC9C0_QMDV03_00_RELEASE1_TRAP_TYPE_TRAP_UNCONDITIONAL: int = 0x1
NVC9C0_QMDV03_00_RELEASE1_TRAP_TYPE_TRAP_CONDITIONAL: int = 0x2
NVC9C0_QMDV03_00_RELEASE1_TRAP_TYPE_TRAP_CONDITIONAL_EXT: int = 0x3
NVC9C0_QMDV03_00_RELEASE1_PAYLOAD64B_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE1_PAYLOAD64B_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE1_STRUCTURE_SIZE_SEMAPHORE_FOUR_WORDS: int = 0x0
NVC9C0_QMDV03_00_RELEASE1_STRUCTURE_SIZE_SEMAPHORE_ONE_WORD: int = 0x1
NVC9C0_QMDV03_00_RELEASE1_STRUCTURE_SIZE_SEMAPHORE_TWO_WORDS: int = 0x2
NVC9C0_QMDV03_00_CONSTANT_BUFFER_PREFETCH_POST_FALSE: int = 0x0
NVC9C0_QMDV03_00_CONSTANT_BUFFER_PREFETCH_POST_TRUE: int = 0x1
NVC9C0_QMDV03_00_CONSTANT_BUFFER_INVALIDATE_FALSE: int = 0x0
NVC9C0_QMDV03_00_CONSTANT_BUFFER_INVALIDATE_TRUE: int = 0x1
NVC9C0_QMDV03_00_PROGRAM_PREFETCH_TYPE_PREFETCH_LAUNCH: int = 0x0
NVC9C0_QMDV03_00_PROGRAM_PREFETCH_TYPE_PREFTECH_POST: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_MEMBAR_TYPE_FE_NONE: int = 0x0
NVC9C0_QMDV03_00_RELEASE2_MEMBAR_TYPE_FE_SYSMEMBAR: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_OP_RED_ADD: int = 0x0
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_OP_RED_MIN: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_OP_RED_MAX: int = 0x2
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_OP_RED_INC: int = 0x3
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_OP_RED_DEC: int = 0x4
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_OP_RED_AND: int = 0x5
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_OP_RED_OR: int = 0x6
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_OP_RED_XOR: int = 0x7
NVC9C0_QMDV03_00_RELEASE2_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE2_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_FORMAT_UNSIGNED: int = 0x0
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_FORMAT_SIGNED: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_ENABLE_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE2_REDUCTION_ENABLE_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_TRAP_TYPE_TRAP_NONE: int = 0x0
NVC9C0_QMDV03_00_RELEASE2_TRAP_TYPE_TRAP_UNCONDITIONAL: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_TRAP_TYPE_TRAP_CONDITIONAL: int = 0x2
NVC9C0_QMDV03_00_RELEASE2_TRAP_TYPE_TRAP_CONDITIONAL_EXT: int = 0x3
NVC9C0_QMDV03_00_RELEASE2_PAYLOAD64B_FALSE: int = 0x0
NVC9C0_QMDV03_00_RELEASE2_PAYLOAD64B_TRUE: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_STRUCTURE_SIZE_SEMAPHORE_FOUR_WORDS: int = 0x0
NVC9C0_QMDV03_00_RELEASE2_STRUCTURE_SIZE_SEMAPHORE_ONE_WORD: int = 0x1
NVC9C0_QMDV03_00_RELEASE2_STRUCTURE_SIZE_SEMAPHORE_TWO_WORDS: int = 0x2
NVC9C0_QMDV03_00_HW_ONLY_SPAN_LIST_HEAD_INDEX_VALID_FALSE: int = 0x0
NVC9C0_QMDV03_00_HW_ONLY_SPAN_LIST_HEAD_INDEX_VALID_TRUE: int = 0x1




class qmdv0204(Structure):
    _fields_ = [
        ("outer_put", c_uint, 31),
        ("outer_overflow", c_uint, 1),
        ("outer_get", c_uint, 31),
        ("outer_sticky_overflow", c_uint, 1),
        ("inner_get", c_uint, 31),
        ("inner_overflow", c_uint, 1),
        ("inner_put", c_uint, 31),
        ("inner_sticky_overflow", c_uint, 1),
        ("qmd_group_id", c_uint, 6),
        ("sm_global_caching_enable", c_uint, 1),
        ("run_cta_in_one_sm_partition", c_uint, 1),
        ("is_queue", c_uint, 1),
        ("add_to_head_of_qmd_group_linked_list", c_uint, 1),
        ("semaphore_release_enable0", c_uint, 1),
        ("semaphore_release_enable1", c_uint, 1),
        ("require_scheduling_pcas", c_uint, 1),
        ("dependent_qmd0_enable", c_uint, 1),
        ("dependent_qmd0_action", c_uint, 3),
        ("dependent_qmd0_prefetch", c_uint, 1),
        ("dependent_qmd1_enable", c_uint, 1),
        ("dependent_qmd1_action", c_uint, 3),
        ("dependent_qmd1_prefetch", c_uint, 1),
        ("dependence_counter", c_uint, 7),
        ("self_copy_on_completion", c_uint, 1),
        ("pad_158_160", c_uint, 1),
        ("circular_queue_size", c_uint, 25),
        ("demote_l2_evict_last", c_uint, 1),
        ("invalidate_texture_header_cache", c_uint, 1),
        ("invalidate_texture_sampler_cache", c_uint, 1),
        ("invalidate_texture_data_cache", c_uint, 1),
        ("invalidate_shader_data_cache", c_uint, 1),
        ("invalidate_instruction_cache", c_uint, 1),
        ("invalidate_shader_constant_cache", c_uint, 1),
        ("cta_raster_width_resume", c_uint, 32),
        ("cta_raster_height_resume", c_uint, 16),
        ("cta_raster_depth_resume", c_uint, 16),
        ("program_prefetch_addr_lower_shifted", c_uint, 32),
        ("circular_queue_addr_lower", c_uint, 32),
        ("circular_queue_addr_upper", c_uint, 8),
        ("pad_327_336", c_uint, 8),
        ("circular_queue_entry_size", c_uint, 16),
        ("cwd_reference_count_id", c_uint, 6),
        ("cwd_reference_count_delta_minus_one", c_uint, 8),
        ("release_membar_type", c_uint, 1),
        ("cwd_reference_count_incr_enable", c_uint, 1),
        ("cwd_membar_type", c_uint, 2),
        ("sequentially_run_ctas", c_uint, 1),
        ("cwd_reference_count_decr_enable", c_uint, 1),
        ("pad_371_378", c_uint, 6),
        ("api_visible_call_limit", c_uint, 1),
        ("pad_378_382", c_uint, 3),
        ("sampler_index", c_uint, 1),
        ("disable_auto_invalidate", c_uint, 1),
        ("cta_raster_width", c_uint, 32),
        ("cta_raster_height", c_uint, 16),
        ("pad_431_448", c_uint, 16),
        ("cta_raster_depth", c_uint, 16),
        ("pad_463_480", c_uint, 16),
        ("dependent_qmd0_pointer", c_uint, 32),
        ("pad_511_522", c_uint, 10),
        ("coalesce_waiting_period", c_uint, 8),
        ("queue_entries_per_cta_log2", c_uint, 5),
        ("pad_534_544", c_uint, 9),
        ("shared_memory_size", c_uint, 18),
        ("min_sm_config_shared_mem_size", c_uint, 7),
        ("max_sm_config_shared_mem_size", c_uint, 7),
        ("qmd_version", c_uint, 4),
        ("qmd_major_version", c_uint, 4),
        ("pad_583_592", c_uint, 8),
        ("cta_thread_dimension0", c_uint, 16),
        ("cta_thread_dimension1", c_uint, 16),
        ("cta_thread_dimension2", c_uint, 16),
        ("constant_buffer_valid_0", c_uint, 1),
        ("constant_buffer_valid_1", c_uint, 1),
        ("constant_buffer_valid_2", c_uint, 1),
        ("constant_buffer_valid_3", c_uint, 1),
        ("constant_buffer_valid_4", c_uint, 1),
        ("constant_buffer_valid_5", c_uint, 1),
        ("constant_buffer_valid_6", c_uint, 1),
        ("constant_buffer_valid_7", c_uint, 1),
        ("register_count_v", c_uint, 9),
        ("target_sm_config_shared_mem_size", c_uint, 7),
        ("free_cta_slots_empty_sm", c_uint, 8),
        ("sm_disable_mask_lower", c_uint, 32),
        ("sm_disable_mask_upper", c_uint, 32),
        ("release0_address_lower", c_uint, 32),
        ("release0_address_upper", c_uint, 8),
        ("pad_775_788", c_uint, 12),
        ("release0_reduction_op", c_uint, 3),
        ("pad_790_792", c_uint, 1),
        ("release0_reduction_format", c_uint, 2),
        ("release0_reduction_enable", c_uint, 1),
        ("pad_794_799", c_uint, 4),
        ("release0_structure_size", c_uint, 1),
        ("release0_payload", c_uint, 32),
        ("release1_address_lower", c_uint, 32),
        ("release1_address_upper", c_uint, 8),
        ("pad_871_884", c_uint, 12),
        ("release1_reduction_op", c_uint, 3),
        ("pad_886_888", c_uint, 1),
        ("release1_reduction_format", c_uint, 2),
        ("release1_reduction_enable", c_uint, 1),
        ("pad_890_895", c_uint, 4),
        ("release1_structure_size", c_uint, 1),
        ("release1_payload", c_uint, 32),
        ("shader_local_memory_low_size", c_uint, 24),
        ("pad_951_955", c_uint, 3),
        ("barrier_count", c_uint, 5),
        ("shader_local_memory_high_size", c_uint, 24),
        ("pad_983_992", c_uint, 8),
        ("program_prefetch_addr_upper_shifted", c_uint, 9),
        ("program_prefetch_size", c_uint, 9),
        ("program_prefetch_type", c_uint, 2),
        ("pad_1011_1016", c_uint, 4),
        ("sass_version", c_uint, 8),
        ("constant_buffer_addr_lower_0", c_uint, 32),
        ("constant_buffer_addr_upper_0", c_uint, 17),
        ("constant_buffer_prefetch_post_0", c_uint, 1),
        ("constant_buffer_invalidate_0", c_uint, 1),
        ("constant_buffer_size_shifted4_0", c_uint, 13),
        ("constant_buffer_addr_lower_1", c_uint, 32),
        ("constant_buffer_addr_upper_1", c_uint, 17),
        ("constant_buffer_prefetch_post_1", c_uint, 1),
        ("constant_buffer_invalidate_1", c_uint, 1),
        ("constant_buffer_size_shifted4_1", c_uint, 13),
        ("constant_buffer_addr_lower_2", c_uint, 32),
        ("constant_buffer_addr_upper_2", c_uint, 17),
        ("constant_buffer_prefetch_post_2", c_uint, 1),
        ("constant_buffer_invalidate_2", c_uint, 1),
        ("constant_buffer_size_shifted4_2", c_uint, 13),
        ("constant_buffer_addr_lower_3", c_uint, 32),
        ("constant_buffer_addr_upper_3", c_uint, 17),
        ("constant_buffer_prefetch_post_3", c_uint, 1),
        ("constant_buffer_invalidate_3", c_uint, 1),
        ("constant_buffer_size_shifted4_3", c_uint, 13),
        ("constant_buffer_addr_lower_4", c_uint, 32),
        ("constant_buffer_addr_upper_4", c_uint, 17),
        ("constant_buffer_prefetch_post_4", c_uint, 1),
        ("constant_buffer_invalidate_4", c_uint, 1),
        ("constant_buffer_size_shifted4_4", c_uint, 13),
        ("constant_buffer_addr_lower_5", c_uint, 32),
        ("constant_buffer_addr_upper_5", c_uint, 17),
        ("constant_buffer_prefetch_post_5", c_uint, 1),
        ("constant_buffer_invalidate_5", c_uint, 1),
        ("constant_buffer_size_shifted4_5", c_uint, 13),
        ("constant_buffer_addr_lower_6", c_uint, 32),
        ("constant_buffer_addr_upper_6", c_uint, 17),
        ("constant_buffer_prefetch_post_6", c_uint, 1),
        ("constant_buffer_invalidate_6", c_uint, 1),
        ("constant_buffer_size_shifted4_6", c_uint, 13),
        ("constant_buffer_addr_lower_7", c_uint, 32),
        ("constant_buffer_addr_upper_7", c_uint, 17),
        ("constant_buffer_prefetch_post_7", c_uint, 1),
        ("constant_buffer_invalidate_7", c_uint, 1),
        ("constant_buffer_size_shifted4_7", c_uint, 13),
        ("program_address_lower", c_uint, 32),
        ("program_address_upper", c_uint, 17),
        ("pad_1584_1600", c_uint, 15),
        ("hw_only_inner_get", c_uint, 31),
        ("hw_only_require_scheduling_pcas", c_uint, 1),
        ("hw_only_inner_put", c_uint, 31),
        ("hw_only_scg_type", c_uint, 1),
        ("hw_only_span_list_head_index", c_uint, 30),
        ("pad_1693_1695", c_uint, 1),
        ("hw_only_span_list_head_index_valid", c_uint, 1),
        ("hw_only_sked_next_qmd_pointer", c_uint, 32),
        ("hw_only_dependence_counter", c_uint, 7),
        ("pad_1734_1760", c_uint, 25),
        ("qmd_spare_h", c_uint, 32),
        ("qmd_spare_i", c_uint, 32),
        ("qmd_spare_j", c_uint, 32),
        ("qmd_spare_k", c_uint, 32),
        ("qmd_spare_l", c_uint, 32),
        ("qmd_spare_m", c_uint, 32),
        ("qmd_spare_n", c_uint, 32),
        ("debug_id_upper", c_uint, 32),
        ("debug_id_lower", c_uint, 32),
    ]


class qmdv0300(Structure):
    _fields_ = [
        ("outer_put", c_uint, 31),
        ("outer_overflow", c_uint, 1),
        ("outer_get", c_uint, 31),
        ("outer_sticky_overflow", c_uint, 1),
        ("inner_get", c_uint, 31),
        ("inner_overflow", c_uint, 1),
        ("inner_put", c_uint, 31),
        ("inner_sticky_overflow", c_uint, 1),
        ("qmd_group_id", c_uint, 6),
        ("sm_global_caching_enable", c_uint, 1),
        ("run_cta_in_one_sm_partition", c_uint, 1),
        ("is_queue", c_uint, 1),
        ("add_to_head_of_qmd_group_linked_list", c_uint, 1),
        ("pad_137_140", c_uint, 2),
        ("require_scheduling_pcas", c_uint, 1),
        ("pad_140_142", c_uint, 1),
        ("dependence_counter", c_uint, 16),
        ("self_copy_on_completion", c_uint, 1),
        ("pad_158_160", c_uint, 1),
        ("circular_queue_size", c_uint, 25),
        ("demote_l2_evict_last", c_uint, 1),
        ("invalidate_texture_header_cache", c_uint, 1),
        ("invalidate_texture_sampler_cache", c_uint, 1),
        ("invalidate_texture_data_cache", c_uint, 1),
        ("invalidate_shader_data_cache", c_uint, 1),
        ("invalidate_instruction_cache", c_uint, 1),
        ("invalidate_shader_constant_cache", c_uint, 1),
        ("cta_raster_width_resume", c_uint, 32),
        ("cta_raster_height_resume", c_uint, 16),
        ("cta_raster_depth_resume", c_uint, 16),
        ("program_prefetch_addr_lower_shifted", c_uint, 32),
        ("circular_queue_addr_lower", c_uint, 32),
        ("circular_queue_addr_upper", c_uint, 8),
        ("pad_327_336", c_uint, 8),
        ("circular_queue_entry_size", c_uint, 16),
        ("cwd_reference_count_id", c_uint, 6),
        ("cwd_reference_count_delta_minus_one", c_uint, 8),
        ("pad_365_367", c_uint, 1),
        ("cwd_reference_count_incr_enable", c_uint, 1),
        ("cwd_membar_type", c_uint, 2),
        ("sequentially_run_ctas", c_uint, 1),
        ("cwd_reference_count_decr_enable", c_uint, 1),
        ("sm_disable_mask_ext_lower", c_uint, 6),
        ("api_visible_call_limit", c_uint, 1),
        ("sm_disable_mask_ext_upper", c_uint, 2),
        ("pad_380_382", c_uint, 1),
        ("sampler_index", c_uint, 1),
        ("disable_auto_invalidate", c_uint, 1),
        ("cta_raster_width", c_uint, 32),
        ("cta_raster_height", c_uint, 16),
        ("pad_431_448", c_uint, 16),
        ("cta_raster_depth", c_uint, 16),
        ("pad_463_480", c_uint, 16),
        ("dependent_qmd0_pointer", c_uint, 32),
        ("dependent_qmd0_enable", c_uint, 1),
        ("dependent_qmd0_action", c_uint, 3),
        ("dependent_qmd0_prefetch", c_uint, 1),
        ("dependent_qmd1_enable", c_uint, 1),
        ("dependent_qmd1_action", c_uint, 3),
        ("dependent_qmd1_prefetch", c_uint, 1),
        ("coalesce_waiting_period", c_uint, 8),
        ("queue_entries_per_cta_log2", c_uint, 5),
        ("occupancy_threshold_shared_mem", c_uint, 8),
        ("cta_launch_queue", c_uint, 1),
        ("shared_memory_size", c_uint, 18),
        ("min_sm_config_shared_mem_size", c_uint, 6),
        ("pad_567_569", c_uint, 1),
        ("max_sm_config_shared_mem_size", c_uint, 6),
        ("pad_574_576", c_uint, 1),
        ("qmd_version", c_uint, 4),
        ("qmd_major_version", c_uint, 4),
        ("occupancy_max_shared_mem", c_uint, 8),
        ("cta_thread_dimension0", c_uint, 16),
        ("cta_thread_dimension1", c_uint, 16),
        ("cta_thread_dimension2", c_uint, 16),
        ("constant_buffer_valid_0", c_uint, 1),
        ("constant_buffer_valid_1", c_uint, 1),
        ("constant_buffer_valid_2", c_uint, 1),
        ("constant_buffer_valid_3", c_uint, 1),
        ("constant_buffer_valid_4", c_uint, 1),
        ("constant_buffer_valid_5", c_uint, 1),
        ("constant_buffer_valid_6", c_uint, 1),
        ("constant_buffer_valid_7", c_uint, 1),
        ("register_count_v", c_uint, 9),
        ("target_sm_config_shared_mem_size", c_uint, 6),
        ("shared_allocation_enable", c_uint, 1),
        ("free_cta_slots_empty_sm", c_uint, 8),
        ("sm_disable_mask_lower", c_uint, 32),
        ("sm_disable_mask_upper", c_uint, 32),
        ("shader_local_memory_low_size", c_uint, 24),
        ("pad_759_763", c_uint, 3),
        ("barrier_count", c_uint, 5),
        ("release0_address_lower", c_uint, 32),
        ("release0_address_upper", c_uint, 8),
        ("pad_807_819", c_uint, 11),
        ("release0_membar_type", c_uint, 1),
        ("release0_reduction_op", c_uint, 3),
        ("release0_enable", c_uint, 1),
        ("release0_reduction_format", c_uint, 2),
        ("release0_reduction_enable", c_uint, 1),
        ("release0_trap_type", c_uint, 2),
        ("release0_payload64b", c_uint, 1),
        ("release0_structure_size", c_uint, 2),
        ("release0_payload_lower", c_uint, 32),
        ("release0_payload_upper", c_uint, 32),
        ("release1_address_lower", c_uint, 32),
        ("release1_address_upper", c_uint, 8),
        ("pad_935_947", c_uint, 11),
        ("release1_membar_type", c_uint, 1),
        ("release1_reduction_op", c_uint, 3),
        ("release1_enable", c_uint, 1),
        ("release1_reduction_format", c_uint, 2),
        ("release1_reduction_enable", c_uint, 1),
        ("release1_trap_type", c_uint, 2),
        ("release1_payload64b", c_uint, 1),
        ("release1_structure_size", c_uint, 2),
        ("release1_payload_lower", c_uint, 32),
        ("release1_payload_upper", c_uint, 32),
        ("constant_buffer_addr_lower_0", c_uint, 32),
        ("constant_buffer_addr_upper_0", c_uint, 17),
        ("constant_buffer_prefetch_post_0", c_uint, 1),
        ("constant_buffer_invalidate_0", c_uint, 1),
        ("constant_buffer_size_shifted4_0", c_uint, 13),
        ("constant_buffer_addr_lower_1", c_uint, 32),
        ("constant_buffer_addr_upper_1", c_uint, 17),
        ("constant_buffer_prefetch_post_1", c_uint, 1),
        ("constant_buffer_invalidate_1", c_uint, 1),
        ("constant_buffer_size_shifted4_1", c_uint, 13),
        ("constant_buffer_addr_lower_2", c_uint, 32),
        ("constant_buffer_addr_upper_2", c_uint, 17),
        ("constant_buffer_prefetch_post_2", c_uint, 1),
        ("constant_buffer_invalidate_2", c_uint, 1),
        ("constant_buffer_size_shifted4_2", c_uint, 13),
        ("constant_buffer_addr_lower_3", c_uint, 32),
        ("constant_buffer_addr_upper_3", c_uint, 17),
        ("constant_buffer_prefetch_post_3", c_uint, 1),
        ("constant_buffer_invalidate_3", c_uint, 1),
        ("constant_buffer_size_shifted4_3", c_uint, 13),
        ("constant_buffer_addr_lower_4", c_uint, 32),
        ("constant_buffer_addr_upper_4", c_uint, 17),
        ("constant_buffer_prefetch_post_4", c_uint, 1),
        ("constant_buffer_invalidate_4", c_uint, 1),
        ("constant_buffer_size_shifted4_4", c_uint, 13),
        ("constant_buffer_addr_lower_5", c_uint, 32),
        ("constant_buffer_addr_upper_5", c_uint, 17),
        ("constant_buffer_prefetch_post_5", c_uint, 1),
        ("constant_buffer_invalidate_5", c_uint, 1),
        ("constant_buffer_size_shifted4_5", c_uint, 13),
        ("constant_buffer_addr_lower_6", c_uint, 32),
        ("constant_buffer_addr_upper_6", c_uint, 17),
        ("constant_buffer_prefetch_post_6", c_uint, 1),
        ("constant_buffer_invalidate_6", c_uint, 1),
        ("constant_buffer_size_shifted4_6", c_uint, 13),
        ("constant_buffer_addr_lower_7", c_uint, 32),
        ("constant_buffer_addr_upper_7", c_uint, 17),
        ("constant_buffer_prefetch_post_7", c_uint, 1),
        ("constant_buffer_invalidate_7", c_uint, 1),
        ("constant_buffer_size_shifted4_7", c_uint, 13),
        ("program_address_lower", c_uint, 32),
        ("program_address_upper", c_uint, 17),
        ("pad_1584_1600", c_uint, 15),
        ("shader_local_memory_high_size", c_uint, 24),
        ("pad_1623_1632", c_uint, 8),
        ("program_prefetch_addr_upper_shifted", c_uint, 9),
        ("program_prefetch_size", c_uint, 9),
        ("program_prefetch_type", c_uint, 2),
        ("pad_1651_1656", c_uint, 4),
        ("sass_version", c_uint, 8),
        ("release2_address_lower", c_uint, 32),
        ("release2_address_upper", c_uint, 8),
        ("pad_1703_1715", c_uint, 11),
        ("release2_membar_type", c_uint, 1),
        ("release2_reduction_op", c_uint, 3),
        ("release2_enable", c_uint, 1),
        ("release2_reduction_format", c_uint, 2),
        ("release2_reduction_enable", c_uint, 1),
        ("release2_trap_type", c_uint, 2),
        ("release2_payload64b", c_uint, 1),
        ("release2_structure_size", c_uint, 2),
        ("release2_payload_lower", c_uint, 32),
        ("release2_payload_upper", c_uint, 32),
        ("occupancy_threshold_warp", c_uint, 8),
        ("occupancy_max_warp", c_uint, 8),
        ("occupancy_threshold_register", c_uint, 8),
        ("occupancy_max_register", c_uint, 8),
        ("hw_only_inner_get", c_uint, 31),
        ("hw_only_require_scheduling_pcas", c_uint, 1),
        ("hw_only_inner_put", c_uint, 31),
        ("pad_1886_1888", c_uint, 1),
        ("hw_only_span_list_head_index", c_uint, 30),
        ("pad_1917_1919", c_uint, 1),
        ("hw_only_span_list_head_index_valid", c_uint, 1),
        ("hw_only_sked_next_qmd_pointer", c_uint, 32),
        ("hw_only_dependence_counter", c_uint, 16),
        ("pad_1967_1984", c_uint, 16),
        ("debug_id_upper", c_uint, 32),
        ("debug_id_lower", c_uint, 32),
    ]






