# AUTOGENERATED: DO NOT EDIT
# Last update date: 2022-11-12 16:44:59.520337

from utils import *


TURING_COMPUTE_A: int = 0xC5C0
NVC5C0_SET_OBJECT: int = 0x0
NVC5C0_NO_OPERATION: int = 0x100
NVC5C0_SET_NOTIFY_A: int = 0x104
NVC5C0_SET_NOTIFY_B: int = 0x108
NVC5C0_NOTIFY: int = 0x10C
NVC5C0_NOTIFY_TYPE_WRITE_ONLY: int = 0x0
NVC5C0_NOTIFY_TYPE_WRITE_THEN_AWAKEN: int = 0x1
NVC5C0_WAIT_FOR_IDLE: int = 0x110
NVC5C0_SET_GLOBAL_RENDER_ENABLE_A: int = 0x130
NVC5C0_SET_GLOBAL_RENDER_ENABLE_B: int = 0x134
NVC5C0_SET_GLOBAL_RENDER_ENABLE_C: int = 0x138
NVC5C0_SET_GLOBAL_RENDER_ENABLE_C_MODE_FALSE: int = 0x0
NVC5C0_SET_GLOBAL_RENDER_ENABLE_C_MODE_TRUE: int = 0x1
NVC5C0_SET_GLOBAL_RENDER_ENABLE_C_MODE_CONDITIONAL: int = 0x2
NVC5C0_SET_GLOBAL_RENDER_ENABLE_C_MODE_RENDER_IF_EQUAL: int = 0x3
NVC5C0_SET_GLOBAL_RENDER_ENABLE_C_MODE_RENDER_IF_NOT_EQUAL: int = 0x4
NVC5C0_SEND_GO_IDLE: int = 0x13C
NVC5C0_PM_TRIGGER: int = 0x140
NVC5C0_PM_TRIGGER_WFI: int = 0x144
NVC5C0_FE_ATOMIC_SEQUENCE_BEGIN: int = 0x148
NVC5C0_FE_ATOMIC_SEQUENCE_END: int = 0x14C
NVC5C0_SET_INSTRUMENTATION_METHOD_HEADER: int = 0x150
NVC5C0_SET_INSTRUMENTATION_METHOD_DATA: int = 0x154
NVC5C0_LINE_LENGTH_IN: int = 0x180
NVC5C0_LINE_COUNT: int = 0x184
NVC5C0_OFFSET_OUT_UPPER: int = 0x188
NVC5C0_OFFSET_OUT: int = 0x18C
NVC5C0_PITCH_OUT: int = 0x190
NVC5C0_SET_DST_BLOCK_SIZE: int = 0x194
NVC5C0_SET_DST_BLOCK_SIZE_WIDTH_ONE_GOB: int = 0x0
NVC5C0_SET_DST_BLOCK_SIZE_HEIGHT_ONE_GOB: int = 0x0
NVC5C0_SET_DST_BLOCK_SIZE_HEIGHT_TWO_GOBS: int = 0x1
NVC5C0_SET_DST_BLOCK_SIZE_HEIGHT_FOUR_GOBS: int = 0x2
NVC5C0_SET_DST_BLOCK_SIZE_HEIGHT_EIGHT_GOBS: int = 0x3
NVC5C0_SET_DST_BLOCK_SIZE_HEIGHT_SIXTEEN_GOBS: int = 0x4
NVC5C0_SET_DST_BLOCK_SIZE_HEIGHT_THIRTYTWO_GOBS: int = 0x5
NVC5C0_SET_DST_BLOCK_SIZE_DEPTH_ONE_GOB: int = 0x0
NVC5C0_SET_DST_BLOCK_SIZE_DEPTH_TWO_GOBS: int = 0x1
NVC5C0_SET_DST_BLOCK_SIZE_DEPTH_FOUR_GOBS: int = 0x2
NVC5C0_SET_DST_BLOCK_SIZE_DEPTH_EIGHT_GOBS: int = 0x3
NVC5C0_SET_DST_BLOCK_SIZE_DEPTH_SIXTEEN_GOBS: int = 0x4
NVC5C0_SET_DST_BLOCK_SIZE_DEPTH_THIRTYTWO_GOBS: int = 0x5
NVC5C0_SET_DST_WIDTH: int = 0x198
NVC5C0_SET_DST_HEIGHT: int = 0x19C
NVC5C0_SET_DST_DEPTH: int = 0x1A0
NVC5C0_SET_DST_LAYER: int = 0x1A4
NVC5C0_SET_DST_ORIGIN_BYTES_X: int = 0x1A8
NVC5C0_SET_DST_ORIGIN_SAMPLES_Y: int = 0x1AC
NVC5C0_LAUNCH_DMA: int = 0x1B0
NVC5C0_LAUNCH_DMA_DST_MEMORY_LAYOUT_BLOCKLINEAR: int = 0x0
NVC5C0_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH: int = 0x1
NVC5C0_LAUNCH_DMA_COMPLETION_TYPE_FLUSH_DISABLE: int = 0x0
NVC5C0_LAUNCH_DMA_COMPLETION_TYPE_FLUSH_ONLY: int = 0x1
NVC5C0_LAUNCH_DMA_COMPLETION_TYPE_RELEASE_SEMAPHORE: int = 0x2
NVC5C0_LAUNCH_DMA_INTERRUPT_TYPE_NONE: int = 0x0
NVC5C0_LAUNCH_DMA_INTERRUPT_TYPE_INTERRUPT: int = 0x1
NVC5C0_LAUNCH_DMA_SEMAPHORE_STRUCT_SIZE_FOUR_WORDS: int = 0x0
NVC5C0_LAUNCH_DMA_SEMAPHORE_STRUCT_SIZE_ONE_WORD: int = 0x1
NVC5C0_LAUNCH_DMA_REDUCTION_ENABLE_FALSE: int = 0x0
NVC5C0_LAUNCH_DMA_REDUCTION_ENABLE_TRUE: int = 0x1
NVC5C0_LAUNCH_DMA_REDUCTION_OP_RED_ADD: int = 0x0
NVC5C0_LAUNCH_DMA_REDUCTION_OP_RED_MIN: int = 0x1
NVC5C0_LAUNCH_DMA_REDUCTION_OP_RED_MAX: int = 0x2
NVC5C0_LAUNCH_DMA_REDUCTION_OP_RED_INC: int = 0x3
NVC5C0_LAUNCH_DMA_REDUCTION_OP_RED_DEC: int = 0x4
NVC5C0_LAUNCH_DMA_REDUCTION_OP_RED_AND: int = 0x5
NVC5C0_LAUNCH_DMA_REDUCTION_OP_RED_OR: int = 0x6
NVC5C0_LAUNCH_DMA_REDUCTION_OP_RED_XOR: int = 0x7
NVC5C0_LAUNCH_DMA_REDUCTION_FORMAT_UNSIGNED_32: int = 0x0
NVC5C0_LAUNCH_DMA_REDUCTION_FORMAT_SIGNED_32: int = 0x1
NVC5C0_LAUNCH_DMA_SYSMEMBAR_DISABLE_FALSE: int = 0x0
NVC5C0_LAUNCH_DMA_SYSMEMBAR_DISABLE_TRUE: int = 0x1
NVC5C0_LOAD_INLINE_DATA: int = 0x1B4
NVC5C0_SET_I2M_SEMAPHORE_A: int = 0x1DC
NVC5C0_SET_I2M_SEMAPHORE_B: int = 0x1E0
NVC5C0_SET_I2M_SEMAPHORE_C: int = 0x1E4
NVC5C0_SET_SM_SCG_CONTROL: int = 0x1E8
NVC5C0_SET_SM_SCG_CONTROL_COMPUTE_IN_GRAPHICS_FALSE: int = 0x0
NVC5C0_SET_SM_SCG_CONTROL_COMPUTE_IN_GRAPHICS_TRUE: int = 0x1
NVC5C0_SET_I2M_SPARE_NOOP00: int = 0x1F0
NVC5C0_SET_I2M_SPARE_NOOP01: int = 0x1F4
NVC5C0_SET_I2M_SPARE_NOOP02: int = 0x1F8
NVC5C0_SET_I2M_SPARE_NOOP03: int = 0x1FC
NVC5C0_SET_VALID_SPAN_OVERFLOW_AREA_A: int = 0x200
NVC5C0_SET_VALID_SPAN_OVERFLOW_AREA_B: int = 0x204
NVC5C0_SET_VALID_SPAN_OVERFLOW_AREA_C: int = 0x208
NVC5C0_PERFMON_TRANSFER: int = 0x210
NVC5C0_SET_QMD_VIRTUALIZATION_BASE_A: int = 0x214
NVC5C0_SET_QMD_VIRTUALIZATION_BASE_B: int = 0x218
NVC5C0_INVALIDATE_SHADER_CACHES: int = 0x21C
NVC5C0_INVALIDATE_SHADER_CACHES_INSTRUCTION_FALSE: int = 0x0
NVC5C0_INVALIDATE_SHADER_CACHES_INSTRUCTION_TRUE: int = 0x1
NVC5C0_INVALIDATE_SHADER_CACHES_DATA_FALSE: int = 0x0
NVC5C0_INVALIDATE_SHADER_CACHES_DATA_TRUE: int = 0x1
NVC5C0_INVALIDATE_SHADER_CACHES_CONSTANT_FALSE: int = 0x0
NVC5C0_INVALIDATE_SHADER_CACHES_CONSTANT_TRUE: int = 0x1
NVC5C0_INVALIDATE_SHADER_CACHES_LOCKS_FALSE: int = 0x0
NVC5C0_INVALIDATE_SHADER_CACHES_LOCKS_TRUE: int = 0x1
NVC5C0_INVALIDATE_SHADER_CACHES_FLUSH_DATA_FALSE: int = 0x0
NVC5C0_INVALIDATE_SHADER_CACHES_FLUSH_DATA_TRUE: int = 0x1
NVC5C0_SET_RESERVED_SW_METHOD00: int = 0x220
NVC5C0_SET_RESERVED_SW_METHOD01: int = 0x224
NVC5C0_SET_RESERVED_SW_METHOD02: int = 0x228
NVC5C0_SET_RESERVED_SW_METHOD03: int = 0x22C
NVC5C0_SET_RESERVED_SW_METHOD04: int = 0x230
NVC5C0_SET_RESERVED_SW_METHOD05: int = 0x234
NVC5C0_SET_RESERVED_SW_METHOD06: int = 0x238
NVC5C0_SET_RESERVED_SW_METHOD07: int = 0x23C
NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_NO_WFI: int = 0x244
NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_NO_WFI_LINES_ALL: int = 0x0
NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_NO_WFI_LINES_ONE: int = 0x1
NVC5C0_SET_CWD_REF_COUNTER: int = 0x248
NVC5C0_SET_RESERVED_SW_METHOD08: int = 0x24C
NVC5C0_SET_RESERVED_SW_METHOD09: int = 0x250
NVC5C0_SET_RESERVED_SW_METHOD10: int = 0x254
NVC5C0_SET_RESERVED_SW_METHOD11: int = 0x258
NVC5C0_SET_RESERVED_SW_METHOD12: int = 0x25C
NVC5C0_SET_RESERVED_SW_METHOD13: int = 0x260
NVC5C0_SET_RESERVED_SW_METHOD14: int = 0x264
NVC5C0_SET_RESERVED_SW_METHOD15: int = 0x268
NVC5C0_SET_SCG_CONTROL: int = 0x270
NVC5C0_SET_SCG_CONTROL_DISABLE_COMPUTE1_LIMIT_IN_ALL_COMPUTE_FALSE: int = 0x0
NVC5C0_SET_SCG_CONTROL_DISABLE_COMPUTE1_LIMIT_IN_ALL_COMPUTE_TRUE: int = 0x1
NVC5C0_SET_COMPUTE_CLASS_VERSION: int = 0x280
NVC5C0_CHECK_COMPUTE_CLASS_VERSION: int = 0x284
NVC5C0_SET_QMD_VERSION: int = 0x288
NVC5C0_CHECK_QMD_VERSION: int = 0x290
NVC5C0_INVALIDATE_SKED_CACHES: int = 0x298
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL: int = 0x29C
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_I2M_ADDR_ENABLE_FALSE: int = 0x0
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_I2M_ADDR_ENABLE_TRUE: int = 0x1
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_I2M_CONSTANT_BUFFER_ENABLE_FALSE: int = 0x0
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_I2M_CONSTANT_BUFFER_ENABLE_TRUE: int = 0x1
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_IQ2M_ADDR_ENABLE_FALSE: int = 0x0
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_IQ2M_ADDR_ENABLE_TRUE: int = 0x1
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_IQ2M_CONSTANT_BUFFER_ENABLE_FALSE: int = 0x0
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_IQ2M_CONSTANT_BUFFER_ENABLE_TRUE: int = 0x1
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_SEND_PCAS_ENABLE_FALSE: int = 0x0
NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_SEND_PCAS_ENABLE_TRUE: int = 0x1
NVC5C0_SET_SHADER_SHARED_MEMORY_WINDOW_A: int = 0x2A0
NVC5C0_SET_SHADER_SHARED_MEMORY_WINDOW_B: int = 0x2A4
NVC5C0_SCG_HYSTERESIS_CONTROL: int = 0x2A8
NVC5C0_SCG_HYSTERESIS_CONTROL_USE_TIMEOUT_ONCE_FALSE: int = 0x0
NVC5C0_SCG_HYSTERESIS_CONTROL_USE_TIMEOUT_ONCE_TRUE: int = 0x1
NVC5C0_SCG_HYSTERESIS_CONTROL_USE_NULL_TIMEOUT_ONCE_FALSE: int = 0x0
NVC5C0_SCG_HYSTERESIS_CONTROL_USE_NULL_TIMEOUT_ONCE_TRUE: int = 0x1
NVC5C0_SET_CWD_SLOT_COUNT: int = 0x2B0
NVC5C0_SEND_PCAS_A: int = 0x2B4
NVC5C0_SEND_PCAS_B: int = 0x2B8
NVC5C0_SEND_SIGNALING_PCAS_B: int = 0x2BC
NVC5C0_SEND_SIGNALING_PCAS_B_INVALIDATE_FALSE: int = 0x0
NVC5C0_SEND_SIGNALING_PCAS_B_INVALIDATE_TRUE: int = 0x1
NVC5C0_SEND_SIGNALING_PCAS_B_SCHEDULE_FALSE: int = 0x0
NVC5C0_SEND_SIGNALING_PCAS_B_SCHEDULE_TRUE: int = 0x1
NVC5C0_SET_SKED_CACHE_CONTROL: int = 0x2CC
NVC5C0_SET_SKED_CACHE_CONTROL_IGNORE_VEID_FALSE: int = 0x0
NVC5C0_SET_SKED_CACHE_CONTROL_IGNORE_VEID_TRUE: int = 0x1
NVC5C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_A: int = 0x2E4
NVC5C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_B: int = 0x2E8
NVC5C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_C: int = 0x2EC
NVC5C0_SET_SPA_VERSION: int = 0x310
NVC5C0_SET_INLINE_QMD_ADDRESS_A: int = 0x318
NVC5C0_SET_INLINE_QMD_ADDRESS_B: int = 0x31C
NVC5C0_SET_FALCON00: int = 0x500
NVC5C0_SET_FALCON01: int = 0x504
NVC5C0_SET_FALCON02: int = 0x508
NVC5C0_SET_FALCON03: int = 0x50C
NVC5C0_SET_FALCON04: int = 0x510
NVC5C0_SET_FALCON05: int = 0x514
NVC5C0_SET_FALCON06: int = 0x518
NVC5C0_SET_FALCON07: int = 0x51C
NVC5C0_SET_FALCON08: int = 0x520
NVC5C0_SET_FALCON09: int = 0x524
NVC5C0_SET_FALCON10: int = 0x528
NVC5C0_SET_FALCON11: int = 0x52C
NVC5C0_SET_FALCON12: int = 0x530
NVC5C0_SET_FALCON13: int = 0x534
NVC5C0_SET_FALCON14: int = 0x538
NVC5C0_SET_FALCON15: int = 0x53C
NVC5C0_SET_FALCON16: int = 0x540
NVC5C0_SET_FALCON17: int = 0x544
NVC5C0_SET_FALCON18: int = 0x548
NVC5C0_SET_FALCON19: int = 0x54C
NVC5C0_SET_FALCON20: int = 0x550
NVC5C0_SET_FALCON21: int = 0x554
NVC5C0_SET_FALCON22: int = 0x558
NVC5C0_SET_FALCON23: int = 0x55C
NVC5C0_SET_FALCON24: int = 0x560
NVC5C0_SET_FALCON25: int = 0x564
NVC5C0_SET_FALCON26: int = 0x568
NVC5C0_SET_FALCON27: int = 0x56C
NVC5C0_SET_FALCON28: int = 0x570
NVC5C0_SET_FALCON29: int = 0x574
NVC5C0_SET_FALCON30: int = 0x578
NVC5C0_SET_FALCON31: int = 0x57C
NVC5C0_SET_SHADER_LOCAL_MEMORY_A: int = 0x790
NVC5C0_SET_SHADER_LOCAL_MEMORY_B: int = 0x794
NVC5C0_SET_SHADER_LOCAL_MEMORY_WINDOW_A: int = 0x7B0
NVC5C0_SET_SHADER_LOCAL_MEMORY_WINDOW_B: int = 0x7B4
NVC5C0_SET_SHADER_CACHE_CONTROL: int = 0xD94
NVC5C0_SET_SHADER_CACHE_CONTROL_ICACHE_PREFETCH_ENABLE_FALSE: int = 0x0
NVC5C0_SET_SHADER_CACHE_CONTROL_ICACHE_PREFETCH_ENABLE_TRUE: int = 0x1
NVC5C0_SET_SM_TIMEOUT_INTERVAL: int = 0xDE4
NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_NO_WFI: int = 0x1288
NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_NO_WFI_LINES_ALL: int = 0x0
NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_NO_WFI_LINES_ONE: int = 0x1
NVC5C0_ACTIVATE_PERF_SETTINGS_FOR_COMPUTE_CONTEXT: int = 0x12A8
NVC5C0_ACTIVATE_PERF_SETTINGS_FOR_COMPUTE_CONTEXT_ALL_FALSE: int = 0x0
NVC5C0_ACTIVATE_PERF_SETTINGS_FOR_COMPUTE_CONTEXT_ALL_TRUE: int = 0x1
NVC5C0_INVALIDATE_SAMPLER_CACHE: int = 0x1330
NVC5C0_INVALIDATE_SAMPLER_CACHE_LINES_ALL: int = 0x0
NVC5C0_INVALIDATE_SAMPLER_CACHE_LINES_ONE: int = 0x1
NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE: int = 0x1334
NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_LINES_ALL: int = 0x0
NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_LINES_ONE: int = 0x1
NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE: int = 0x1338
NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_LINES_ALL: int = 0x0
NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_LINES_ONE: int = 0x1
NVC5C0_INVALIDATE_SAMPLER_CACHE_NO_WFI: int = 0x1424
NVC5C0_INVALIDATE_SAMPLER_CACHE_NO_WFI_LINES_ALL: int = 0x0
NVC5C0_INVALIDATE_SAMPLER_CACHE_NO_WFI_LINES_ONE: int = 0x1
NVC5C0_SET_SHADER_EXCEPTIONS: int = 0x1528
NVC5C0_SET_SHADER_EXCEPTIONS_ENABLE_FALSE: int = 0x0
NVC5C0_SET_SHADER_EXCEPTIONS_ENABLE_TRUE: int = 0x1
NVC5C0_SET_RENDER_ENABLE_A: int = 0x1550
NVC5C0_SET_RENDER_ENABLE_B: int = 0x1554
NVC5C0_SET_RENDER_ENABLE_C: int = 0x1558
NVC5C0_SET_RENDER_ENABLE_C_MODE_FALSE: int = 0x0
NVC5C0_SET_RENDER_ENABLE_C_MODE_TRUE: int = 0x1
NVC5C0_SET_RENDER_ENABLE_C_MODE_CONDITIONAL: int = 0x2
NVC5C0_SET_RENDER_ENABLE_C_MODE_RENDER_IF_EQUAL: int = 0x3
NVC5C0_SET_RENDER_ENABLE_C_MODE_RENDER_IF_NOT_EQUAL: int = 0x4
NVC5C0_SET_TEX_SAMPLER_POOL_A: int = 0x155C
NVC5C0_SET_TEX_SAMPLER_POOL_B: int = 0x1560
NVC5C0_SET_TEX_SAMPLER_POOL_C: int = 0x1564
NVC5C0_SET_TEX_HEADER_POOL_A: int = 0x1574
NVC5C0_SET_TEX_HEADER_POOL_B: int = 0x1578
NVC5C0_SET_TEX_HEADER_POOL_C: int = 0x157C
NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI: int = 0x1698
NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_INSTRUCTION_FALSE: int = 0x0
NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_INSTRUCTION_TRUE: int = 0x1
NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_GLOBAL_DATA_FALSE: int = 0x0
NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_GLOBAL_DATA_TRUE: int = 0x1
NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_CONSTANT_FALSE: int = 0x0
NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_CONSTANT_TRUE: int = 0x1
NVC5C0_SET_RENDER_ENABLE_OVERRIDE: int = 0x1944
NVC5C0_SET_RENDER_ENABLE_OVERRIDE_MODE_USE_RENDER_ENABLE: int = 0x0
NVC5C0_SET_RENDER_ENABLE_OVERRIDE_MODE_ALWAYS_RENDER: int = 0x1
NVC5C0_SET_RENDER_ENABLE_OVERRIDE_MODE_NEVER_RENDER: int = 0x2
NVC5C0_PIPE_NOP: int = 0x1A2C
NVC5C0_SET_SPARE00: int = 0x1A30
NVC5C0_SET_SPARE01: int = 0x1A34
NVC5C0_SET_SPARE02: int = 0x1A38
NVC5C0_SET_SPARE03: int = 0x1A3C
NVC5C0_SET_REPORT_SEMAPHORE_A: int = 0x1B00
NVC5C0_SET_REPORT_SEMAPHORE_B: int = 0x1B04
NVC5C0_SET_REPORT_SEMAPHORE_C: int = 0x1B08
NVC5C0_SET_REPORT_SEMAPHORE_D: int = 0x1B0C
NVC5C0_SET_REPORT_SEMAPHORE_D_OPERATION_RELEASE: int = 0x0
NVC5C0_SET_REPORT_SEMAPHORE_D_OPERATION_TRAP: int = 0x3
NVC5C0_SET_REPORT_SEMAPHORE_D_AWAKEN_ENABLE_FALSE: int = 0x0
NVC5C0_SET_REPORT_SEMAPHORE_D_AWAKEN_ENABLE_TRUE: int = 0x1
NVC5C0_SET_REPORT_SEMAPHORE_D_STRUCTURE_SIZE_FOUR_WORDS: int = 0x0
NVC5C0_SET_REPORT_SEMAPHORE_D_STRUCTURE_SIZE_ONE_WORD: int = 0x1
NVC5C0_SET_REPORT_SEMAPHORE_D_FLUSH_DISABLE_FALSE: int = 0x0
NVC5C0_SET_REPORT_SEMAPHORE_D_FLUSH_DISABLE_TRUE: int = 0x1
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_ENABLE_FALSE: int = 0x0
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_ENABLE_TRUE: int = 0x1
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP_RED_ADD: int = 0x0
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP_RED_MIN: int = 0x1
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP_RED_MAX: int = 0x2
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP_RED_INC: int = 0x3
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP_RED_DEC: int = 0x4
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP_RED_AND: int = 0x5
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP_RED_OR: int = 0x6
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP_RED_XOR: int = 0x7
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_FORMAT_UNSIGNED_32: int = 0x0
NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_FORMAT_SIGNED_32: int = 0x1
NVC5C0_SET_REPORT_SEMAPHORE_D_CONDITIONAL_TRAP_FALSE: int = 0x0
NVC5C0_SET_REPORT_SEMAPHORE_D_CONDITIONAL_TRAP_TRUE: int = 0x1
NVC5C0_SET_TRAP_HANDLER_A: int = 0x25F8
NVC5C0_SET_TRAP_HANDLER_B: int = 0x25FC
NVC5C0_SET_BINDLESS_TEXTURE: int = 0x2608
NVC5C0_ENABLE_SHADER_PERFORMANCE_SNAPSHOT_COUNTER: int = 0x3334
NVC5C0_DISABLE_SHADER_PERFORMANCE_SNAPSHOT_COUNTER: int = 0x3338
NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_TRAP_CONTROL: int = 0x33DC
NVC5C0_START_SHADER_PERFORMANCE_COUNTER: int = 0x33E0
NVC5C0_STOP_SHADER_PERFORMANCE_COUNTER: int = 0x33E4
NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_SCTL_FILTER: int = 0x33E8
NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CORE_MIO_FILTER: int = 0x33EC


def NVC5C0_SET_OBJECT_CLASS_ID(value: int) -> int:
    return set_bits(0, 15, value)


def NVC5C0_SET_OBJECT_ENGINE_ID(value: int) -> int:
    return set_bits(16, 4, value)


def NVC5C0_NO_OPERATION_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_NOTIFY_A_ADDRESS_UPPER(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_NOTIFY_B_ADDRESS_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_NOTIFY_TYPE(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_WAIT_FOR_IDLE_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_GLOBAL_RENDER_ENABLE_A_OFFSET_UPPER(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_GLOBAL_RENDER_ENABLE_B_OFFSET_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_GLOBAL_RENDER_ENABLE_C_MODE(value: int) -> int:
    return set_bits(0, 2, value)


def NVC5C0_SEND_GO_IDLE_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_PM_TRIGGER_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_PM_TRIGGER_WFI_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_FE_ATOMIC_SEQUENCE_BEGIN_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_FE_ATOMIC_SEQUENCE_END_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_INSTRUMENTATION_METHOD_HEADER_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_INSTRUMENTATION_METHOD_DATA_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_LINE_LENGTH_IN_VALUE(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_LINE_COUNT_VALUE(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_OFFSET_OUT_UPPER_VALUE(value: int) -> int:
    return set_bits(0, 16, value)


def NVC5C0_OFFSET_OUT_VALUE(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_PITCH_OUT_VALUE(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_DST_BLOCK_SIZE_WIDTH(value: int) -> int:
    return set_bits(0, 3, value)


def NVC5C0_SET_DST_BLOCK_SIZE_HEIGHT(value: int) -> int:
    return set_bits(4, 3, value)


def NVC5C0_SET_DST_BLOCK_SIZE_DEPTH(value: int) -> int:
    return set_bits(8, 3, value)


def NVC5C0_SET_DST_WIDTH_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_DST_HEIGHT_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_DST_DEPTH_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_DST_LAYER_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_DST_ORIGIN_BYTES_X_V(value: int) -> int:
    return set_bits(0, 20, value)


def NVC5C0_SET_DST_ORIGIN_SAMPLES_Y_V(value: int) -> int:
    return set_bits(0, 16, value)


def NVC5C0_LAUNCH_DMA_DST_MEMORY_LAYOUT(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_LAUNCH_DMA_COMPLETION_TYPE(value: int) -> int:
    return set_bits(4, 1, value)


def NVC5C0_LAUNCH_DMA_INTERRUPT_TYPE(value: int) -> int:
    return set_bits(8, 1, value)


def NVC5C0_LAUNCH_DMA_SEMAPHORE_STRUCT_SIZE(value: int) -> int:
    return set_bits(12, 0, value)


def NVC5C0_LAUNCH_DMA_REDUCTION_ENABLE(value: int) -> int:
    return set_bits(1, 0, value)


def NVC5C0_LAUNCH_DMA_REDUCTION_OP(value: int) -> int:
    return set_bits(13, 2, value)


def NVC5C0_LAUNCH_DMA_REDUCTION_FORMAT(value: int) -> int:
    return set_bits(2, 1, value)


def NVC5C0_LAUNCH_DMA_SYSMEMBAR_DISABLE(value: int) -> int:
    return set_bits(6, 0, value)


def NVC5C0_LOAD_INLINE_DATA_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_I2M_SEMAPHORE_A_OFFSET_UPPER(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_I2M_SEMAPHORE_B_OFFSET_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_I2M_SEMAPHORE_C_PAYLOAD(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SM_SCG_CONTROL_COMPUTE_IN_GRAPHICS(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SET_I2M_SPARE_NOOP00_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_I2M_SPARE_NOOP01_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_I2M_SPARE_NOOP02_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_I2M_SPARE_NOOP03_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_VALID_SPAN_OVERFLOW_AREA_A_ADDRESS_UPPER(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_VALID_SPAN_OVERFLOW_AREA_B_ADDRESS_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_VALID_SPAN_OVERFLOW_AREA_C_SIZE(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_PERFMON_TRANSFER_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_QMD_VIRTUALIZATION_BASE_A_ADDRESS_UPPER(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_QMD_VIRTUALIZATION_BASE_B_ADDRESS_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_INVALIDATE_SHADER_CACHES_INSTRUCTION(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_SHADER_CACHES_DATA(value: int) -> int:
    return set_bits(4, 0, value)


def NVC5C0_INVALIDATE_SHADER_CACHES_CONSTANT(value: int) -> int:
    return set_bits(12, 0, value)


def NVC5C0_INVALIDATE_SHADER_CACHES_LOCKS(value: int) -> int:
    return set_bits(1, 0, value)


def NVC5C0_INVALIDATE_SHADER_CACHES_FLUSH_DATA(value: int) -> int:
    return set_bits(2, 0, value)


def NVC5C0_SET_RESERVED_SW_METHOD00_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD01_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD02_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD03_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD04_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD05_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD06_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD07_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_NO_WFI_LINES(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_NO_WFI_TAG(value: int) -> int:
    return set_bits(4, 21, value)


def NVC5C0_SET_CWD_REF_COUNTER_SELECT(value: int) -> int:
    return set_bits(0, 5, value)


def NVC5C0_SET_CWD_REF_COUNTER_VALUE(value: int) -> int:
    return set_bits(8, 15, value)


def NVC5C0_SET_RESERVED_SW_METHOD08_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD09_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD10_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD11_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD12_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD13_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD14_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RESERVED_SW_METHOD15_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SCG_CONTROL_COMPUTE1_MAX_SM_COUNT(value: int) -> int:
    return set_bits(0, 8, value)


def NVC5C0_SET_SCG_CONTROL_COMPUTE1_MIN_SM_COUNT(value: int) -> int:
    return set_bits(12, 8, value)


def NVC5C0_SET_SCG_CONTROL_DISABLE_COMPUTE1_LIMIT_IN_ALL_COMPUTE(value: int) -> int:
    return set_bits(24, 0, value)


def NVC5C0_SET_COMPUTE_CLASS_VERSION_CURRENT(value: int) -> int:
    return set_bits(0, 15, value)


def NVC5C0_SET_COMPUTE_CLASS_VERSION_OLDEST_SUPPORTED(value: int) -> int:
    return set_bits(16, 15, value)


def NVC5C0_CHECK_COMPUTE_CLASS_VERSION_CURRENT(value: int) -> int:
    return set_bits(0, 15, value)


def NVC5C0_CHECK_COMPUTE_CLASS_VERSION_OLDEST_SUPPORTED(value: int) -> int:
    return set_bits(16, 15, value)


def NVC5C0_SET_QMD_VERSION_CURRENT(value: int) -> int:
    return set_bits(0, 15, value)


def NVC5C0_SET_QMD_VERSION_OLDEST_SUPPORTED(value: int) -> int:
    return set_bits(16, 15, value)


def NVC5C0_CHECK_QMD_VERSION_CURRENT(value: int) -> int:
    return set_bits(0, 15, value)


def NVC5C0_CHECK_QMD_VERSION_OLDEST_SUPPORTED(value: int) -> int:
    return set_bits(16, 15, value)


def NVC5C0_INVALIDATE_SKED_CACHES_V(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_CONSTANT_BUFFER_MASK(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_I2M_ADDR_ENABLE(value: int) -> int:
    return set_bits(8, 0, value)


def NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_I2M_CONSTANT_BUFFER_ENABLE(value: int) -> int:
    return set_bits(12, 0, value)


def NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_IQ2M_ADDR_ENABLE(value: int) -> int:
    return set_bits(16, 0, value)


def NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_IQ2M_CONSTANT_BUFFER_ENABLE(value: int) -> int:
    return set_bits(20, 0, value)


def NVC5C0_SET_QMD_VIRTUALIZATION_CONTROL_SEND_PCAS_ENABLE(value: int) -> int:
    return set_bits(24, 0, value)


def NVC5C0_SET_SHADER_SHARED_MEMORY_WINDOW_A_BASE_ADDRESS_UPPER(value: int) -> int:
    return set_bits(0, 16, value)


def NVC5C0_SET_SHADER_SHARED_MEMORY_WINDOW_B_BASE_ADDRESS(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SCG_HYSTERESIS_CONTROL_USE_TIMEOUT_ONCE(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SCG_HYSTERESIS_CONTROL_USE_NULL_TIMEOUT_ONCE(value: int) -> int:
    return set_bits(1, 0, value)


def NVC5C0_SET_CWD_SLOT_COUNT_V(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SEND_PCAS_A_QMD_ADDRESS_SHIFTED8(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SEND_PCAS_B_FROM(value: int) -> int:
    return set_bits(0, 23, value)


def NVC5C0_SEND_PCAS_B_DELTA(value: int) -> int:
    return set_bits(24, 7, value)


def NVC5C0_SEND_SIGNALING_PCAS_B_INVALIDATE(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SEND_SIGNALING_PCAS_B_SCHEDULE(value: int) -> int:
    return set_bits(1, 0, value)


def NVC5C0_SET_SKED_CACHE_CONTROL_IGNORE_VEID(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_A_SIZE_UPPER(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_B_SIZE_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_C_MAX_SM_COUNT(value: int) -> int:
    return set_bits(0, 8, value)


def NVC5C0_SET_SPA_VERSION_MINOR(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_SPA_VERSION_MAJOR(value: int) -> int:
    return set_bits(8, 7, value)


def NVC5C0_SET_INLINE_QMD_ADDRESS_A_QMD_ADDRESS_SHIFTED8_UPPER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_INLINE_QMD_ADDRESS_B_QMD_ADDRESS_SHIFTED8_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_LOAD_INLINE_QMD_DATA_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON00_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON01_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON02_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON03_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON04_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON05_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON06_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON07_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON08_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON09_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON10_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON11_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON12_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON13_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON14_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON15_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON16_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON17_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON18_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON19_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON20_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON21_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON22_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON23_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON24_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON25_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON26_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON27_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON28_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON29_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON30_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_FALCON31_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SHADER_LOCAL_MEMORY_A_ADDRESS_UPPER(value: int) -> int:
    return set_bits(0, 16, value)


def NVC5C0_SET_SHADER_LOCAL_MEMORY_B_ADDRESS_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SHADER_LOCAL_MEMORY_WINDOW_A_BASE_ADDRESS_UPPER(value: int) -> int:
    return set_bits(0, 16, value)


def NVC5C0_SET_SHADER_LOCAL_MEMORY_WINDOW_B_BASE_ADDRESS(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SHADER_CACHE_CONTROL_ICACHE_PREFETCH_ENABLE(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SET_SCG_COMPUTE_SCHEDULING_PARAMETERS_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SM_TIMEOUT_INTERVAL_COUNTER_BIT(value: int) -> int:
    return set_bits(0, 5, value)


def NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_NO_WFI_LINES(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_NO_WFI_TAG(value: int) -> int:
    return set_bits(4, 21, value)


def NVC5C0_ACTIVATE_PERF_SETTINGS_FOR_COMPUTE_CONTEXT_ALL(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_SAMPLER_CACHE_LINES(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_SAMPLER_CACHE_TAG(value: int) -> int:
    return set_bits(4, 21, value)


def NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_LINES(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_TEXTURE_HEADER_CACHE_TAG(value: int) -> int:
    return set_bits(4, 21, value)


def NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_LINES(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_TEXTURE_DATA_CACHE_TAG(value: int) -> int:
    return set_bits(4, 21, value)


def NVC5C0_INVALIDATE_SAMPLER_CACHE_NO_WFI_LINES(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_SAMPLER_CACHE_NO_WFI_TAG(value: int) -> int:
    return set_bits(4, 21, value)


def NVC5C0_SET_SHADER_EXCEPTIONS_ENABLE(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SET_RENDER_ENABLE_A_OFFSET_UPPER(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_RENDER_ENABLE_B_OFFSET_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_RENDER_ENABLE_C_MODE(value: int) -> int:
    return set_bits(0, 2, value)


def NVC5C0_SET_TEX_SAMPLER_POOL_A_OFFSET_UPPER(value: int) -> int:
    return set_bits(0, 16, value)


def NVC5C0_SET_TEX_SAMPLER_POOL_B_OFFSET_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_TEX_SAMPLER_POOL_C_MAXIMUM_INDEX(value: int) -> int:
    return set_bits(0, 19, value)


def NVC5C0_SET_TEX_HEADER_POOL_A_OFFSET_UPPER(value: int) -> int:
    return set_bits(0, 16, value)


def NVC5C0_SET_TEX_HEADER_POOL_B_OFFSET_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_TEX_HEADER_POOL_C_MAXIMUM_INDEX(value: int) -> int:
    return set_bits(0, 21, value)


def NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_INSTRUCTION(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_GLOBAL_DATA(value: int) -> int:
    return set_bits(4, 0, value)


def NVC5C0_INVALIDATE_SHADER_CACHES_NO_WFI_CONSTANT(value: int) -> int:
    return set_bits(12, 0, value)


def NVC5C0_SET_RENDER_ENABLE_OVERRIDE_MODE(value: int) -> int:
    return set_bits(0, 1, value)


def NVC5C0_PIPE_NOP_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SPARE00_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SPARE01_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SPARE02_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SPARE03_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_REPORT_SEMAPHORE_A_OFFSET_UPPER(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_REPORT_SEMAPHORE_B_OFFSET_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_REPORT_SEMAPHORE_C_PAYLOAD(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_REPORT_SEMAPHORE_D_OPERATION(value: int) -> int:
    return set_bits(0, 1, value)


def NVC5C0_SET_REPORT_SEMAPHORE_D_AWAKEN_ENABLE(value: int) -> int:
    return set_bits(20, 0, value)


def NVC5C0_SET_REPORT_SEMAPHORE_D_STRUCTURE_SIZE(value: int) -> int:
    return set_bits(28, 0, value)


def NVC5C0_SET_REPORT_SEMAPHORE_D_FLUSH_DISABLE(value: int) -> int:
    return set_bits(2, 0, value)


def NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_ENABLE(value: int) -> int:
    return set_bits(3, 0, value)


def NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_OP(value: int) -> int:
    return set_bits(9, 2, value)


def NVC5C0_SET_REPORT_SEMAPHORE_D_REDUCTION_FORMAT(value: int) -> int:
    return set_bits(17, 1, value)


def NVC5C0_SET_REPORT_SEMAPHORE_D_CONDITIONAL_TRAP(value: int) -> int:
    return set_bits(19, 0, value)


def NVC5C0_SET_TRAP_HANDLER_A_ADDRESS_UPPER(value: int) -> int:
    return set_bits(0, 16, value)


def NVC5C0_SET_TRAP_HANDLER_B_ADDRESS_LOWER(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_BINDLESS_TEXTURE_CONSTANT_BUFFER_SLOT_SELECT(value: int) -> int:
    return set_bits(0, 2, value)


def NVC5C0_SET_SHADER_PERFORMANCE_SNAPSHOT_COUNTER_VALUE_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SHADER_PERFORMANCE_SNAPSHOT_COUNTER_VALUE_UPPER_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_ENABLE_SHADER_PERFORMANCE_SNAPSHOT_COUNTER_V(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_DISABLE_SHADER_PERFORMANCE_SNAPSHOT_COUNTER_V(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_VALUE_UPPER_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_VALUE_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_EVENT_EVENT(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_EVENT0(value: int) -> int:
    return set_bits(0, 1, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_BIT_SELECT0(value: int) -> int:
    return set_bits(2, 2, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_EVENT1(value: int) -> int:
    return set_bits(5, 1, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_BIT_SELECT1(value: int) -> int:
    return set_bits(7, 2, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_EVENT2(value: int) -> int:
    return set_bits(10, 1, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_BIT_SELECT2(value: int) -> int:
    return set_bits(12, 2, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_EVENT3(value: int) -> int:
    return set_bits(15, 1, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_BIT_SELECT3(value: int) -> int:
    return set_bits(17, 2, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_EVENT4(value: int) -> int:
    return set_bits(20, 1, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_BIT_SELECT4(value: int) -> int:
    return set_bits(22, 2, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_EVENT5(value: int) -> int:
    return set_bits(25, 1, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_BIT_SELECT5(value: int) -> int:
    return set_bits(27, 2, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_A_SPARE(value: int) -> int:
    return set_bits(30, 1, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_B_EDGE(value: int) -> int:
    return set_bits(0, 0, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_B_MODE(value: int) -> int:
    return set_bits(1, 1, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_B_WINDOWED(value: int) -> int:
    return set_bits(3, 0, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CONTROL_B_FUNC(value: int) -> int:
    return set_bits(4, 15, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_TRAP_CONTROL_MASK(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_START_SHADER_PERFORMANCE_COUNTER_COUNTER_MASK(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_STOP_SHADER_PERFORMANCE_COUNTER_COUNTER_MASK(value: int) -> int:
    return set_bits(0, 7, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_SCTL_FILTER_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_SHADER_PERFORMANCE_COUNTER_CORE_MIO_FILTER_V(value: int) -> int:
    return set_bits(0, 31, value)


def NVC5C0_SET_MME_SHADOW_SCRATCH_V(value: int) -> int:
    return set_bits(0, 31, value)








