# AUTOGENERATED: DO NOT EDIT
# Last update date: 2022-08-08 16:14:55.339065

from ctypes import *


NVB1C0_QMDV00_06_QMD_RESERVED_V1_K_FALSE: int = 0x0
NVB1C0_QMDV00_06_QMD_RESERVED_V1_K_TRUE: int = 0x1
NVB1C0_QMDV00_06_QMD_RESERVED_V1_L_FALSE: int = 0x0
NVB1C0_QMDV00_06_QMD_RESERVED_V1_L_TRUE: int = 0x1
NVB1C0_QMDV00_06_SEMAPHORE_RELEASE_ENABLE0_FALSE: int = 0x0
NVB1C0_QMDV00_06_SEMAPHORE_RELEASE_ENABLE0_TRUE: int = 0x1
NVB1C0_QMDV00_06_SEMAPHORE_RELEASE_ENABLE1_FALSE: int = 0x0
NVB1C0_QMDV00_06_SEMAPHORE_RELEASE_ENABLE1_TRUE: int = 0x1
NVB1C0_QMDV00_06_QMD_RESERVED_V1_N_FALSE: int = 0x0
NVB1C0_QMDV00_06_QMD_RESERVED_V1_N_TRUE: int = 0x1
NVB1C0_QMDV00_06_INVALIDATE_TEXTURE_HEADER_CACHE_FALSE: int = 0x0
NVB1C0_QMDV00_06_INVALIDATE_TEXTURE_HEADER_CACHE_TRUE: int = 0x1
NVB1C0_QMDV00_06_INVALIDATE_TEXTURE_SAMPLER_CACHE_FALSE: int = 0x0
NVB1C0_QMDV00_06_INVALIDATE_TEXTURE_SAMPLER_CACHE_TRUE: int = 0x1
NVB1C0_QMDV00_06_INVALIDATE_TEXTURE_DATA_CACHE_FALSE: int = 0x0
NVB1C0_QMDV00_06_INVALIDATE_TEXTURE_DATA_CACHE_TRUE: int = 0x1
NVB1C0_QMDV00_06_INVALIDATE_SHADER_DATA_CACHE_FALSE: int = 0x0
NVB1C0_QMDV00_06_INVALIDATE_SHADER_DATA_CACHE_TRUE: int = 0x1
NVB1C0_QMDV00_06_INVALIDATE_INSTRUCTION_CACHE_FALSE: int = 0x0
NVB1C0_QMDV00_06_INVALIDATE_INSTRUCTION_CACHE_TRUE: int = 0x1
NVB1C0_QMDV00_06_INVALIDATE_SHADER_CONSTANT_CACHE_FALSE: int = 0x0
NVB1C0_QMDV00_06_INVALIDATE_SHADER_CONSTANT_CACHE_TRUE: int = 0x1
NVB1C0_QMDV00_06_RELEASE_MEMBAR_TYPE_FE_NONE: int = 0x0
NVB1C0_QMDV00_06_RELEASE_MEMBAR_TYPE_FE_SYSMEMBAR: int = 0x1
NVB1C0_QMDV00_06_CWD_MEMBAR_TYPE_L1_NONE: int = 0x0
NVB1C0_QMDV00_06_CWD_MEMBAR_TYPE_L1_SYSMEMBAR: int = 0x1
NVB1C0_QMDV00_06_CWD_MEMBAR_TYPE_L1_MEMBAR: int = 0x3
NVB1C0_QMDV00_06_QMD_RESERVED_V1_T_FALSE: int = 0x0
NVB1C0_QMDV00_06_QMD_RESERVED_V1_T_TRUE: int = 0x1
NVB1C0_QMDV00_06_QMD_RESERVED_V1_U_FALSE: int = 0x0
NVB1C0_QMDV00_06_QMD_RESERVED_V1_U_TRUE: int = 0x1
NVB1C0_QMDV00_06_THROTTLED_FALSE: int = 0x0
NVB1C0_QMDV00_06_THROTTLED_TRUE: int = 0x1
NVB1C0_QMDV00_06_API_VISIBLE_CALL_LIMIT__32: int = 0x0
NVB1C0_QMDV00_06_API_VISIBLE_CALL_LIMIT_NO_CHECK: int = 0x1
NVB1C0_QMDV00_06_SHARED_MEMORY_BANK_MAPPING_FOUR_BYTES_PER_BANK: int = 0x0
NVB1C0_QMDV00_06_SHARED_MEMORY_BANK_MAPPING_EIGHT_BYTES_PER_BANK: int = 0x1
NVB1C0_QMDV00_06_SAMPLER_INDEX_INDEPENDENTLY: int = 0x0
NVB1C0_QMDV00_06_SAMPLER_INDEX_VIA_HEADER_INDEX: int = 0x1
NVB1C0_QMDV00_06_QMD_RESERVED_V1_W_FALSE: int = 0x0
NVB1C0_QMDV00_06_QMD_RESERVED_V1_W_TRUE: int = 0x1
NVB1C0_QMDV00_06_CONSTANT_BUFFER_VALID_FALSE: int = 0x0
NVB1C0_QMDV00_06_CONSTANT_BUFFER_VALID_TRUE: int = 0x1
NVB1C0_QMDV00_06_L1_CONFIGURATION_DIRECTLY_ADDRESSABLE_MEMORY_SIZE_16KB: int = 0x1
NVB1C0_QMDV00_06_L1_CONFIGURATION_DIRECTLY_ADDRESSABLE_MEMORY_SIZE_32KB: int = 0x2
NVB1C0_QMDV00_06_L1_CONFIGURATION_DIRECTLY_ADDRESSABLE_MEMORY_SIZE_48KB: int = 0x3
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_OP_RED_ADD: int = 0x0
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_OP_RED_MIN: int = 0x1
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_OP_RED_MAX: int = 0x2
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_OP_RED_INC: int = 0x3
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_OP_RED_DEC: int = 0x4
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_OP_RED_AND: int = 0x5
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_OP_RED_OR: int = 0x6
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_OP_RED_XOR: int = 0x7
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_FORMAT_UNSIGNED_32: int = 0x0
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_FORMAT_SIGNED_32: int = 0x1
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_ENABLE_FALSE: int = 0x0
NVB1C0_QMDV00_06_RELEASE0_REDUCTION_ENABLE_TRUE: int = 0x1
NVB1C0_QMDV00_06_RELEASE0_STRUCTURE_SIZE_FOUR_WORDS: int = 0x0
NVB1C0_QMDV00_06_RELEASE0_STRUCTURE_SIZE_ONE_WORD: int = 0x1
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_OP_RED_ADD: int = 0x0
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_OP_RED_MIN: int = 0x1
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_OP_RED_MAX: int = 0x2
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_OP_RED_INC: int = 0x3
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_OP_RED_DEC: int = 0x4
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_OP_RED_AND: int = 0x5
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_OP_RED_OR: int = 0x6
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_OP_RED_XOR: int = 0x7
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_FORMAT_UNSIGNED_32: int = 0x0
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_FORMAT_SIGNED_32: int = 0x1
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_ENABLE_FALSE: int = 0x0
NVB1C0_QMDV00_06_RELEASE1_REDUCTION_ENABLE_TRUE: int = 0x1
NVB1C0_QMDV00_06_RELEASE1_STRUCTURE_SIZE_FOUR_WORDS: int = 0x0
NVB1C0_QMDV00_06_RELEASE1_STRUCTURE_SIZE_ONE_WORD: int = 0x1
NVB1C0_QMDV00_06_CONSTANT_BUFFER_INVALIDATE_FALSE: int = 0x0
NVB1C0_QMDV00_06_CONSTANT_BUFFER_INVALIDATE_TRUE: int = 0x1
NVB1C0_QMDV01_07_RUN_CTA_IN_ONE_SM_PARTITION_FALSE: int = 0x0
NVB1C0_QMDV01_07_RUN_CTA_IN_ONE_SM_PARTITION_TRUE: int = 0x1
NVB1C0_QMDV01_07_IS_QUEUE_FALSE: int = 0x0
NVB1C0_QMDV01_07_IS_QUEUE_TRUE: int = 0x1
NVB1C0_QMDV01_07_ADD_TO_HEAD_OF_QMD_GROUP_LINKED_LIST_FALSE: int = 0x0
NVB1C0_QMDV01_07_ADD_TO_HEAD_OF_QMD_GROUP_LINKED_LIST_TRUE: int = 0x1
NVB1C0_QMDV01_07_SEMAPHORE_RELEASE_ENABLE0_FALSE: int = 0x0
NVB1C0_QMDV01_07_SEMAPHORE_RELEASE_ENABLE0_TRUE: int = 0x1
NVB1C0_QMDV01_07_SEMAPHORE_RELEASE_ENABLE1_FALSE: int = 0x0
NVB1C0_QMDV01_07_SEMAPHORE_RELEASE_ENABLE1_TRUE: int = 0x1
NVB1C0_QMDV01_07_REQUIRE_SCHEDULING_PCAS_FALSE: int = 0x0
NVB1C0_QMDV01_07_REQUIRE_SCHEDULING_PCAS_TRUE: int = 0x1
NVB1C0_QMDV01_07_DEPENDENT_QMD_SCHEDULE_ENABLE_FALSE: int = 0x0
NVB1C0_QMDV01_07_DEPENDENT_QMD_SCHEDULE_ENABLE_TRUE: int = 0x1
NVB1C0_QMDV01_07_DEPENDENT_QMD_TYPE_QUEUE: int = 0x0
NVB1C0_QMDV01_07_DEPENDENT_QMD_TYPE_GRID: int = 0x1
NVB1C0_QMDV01_07_DEPENDENT_QMD_FIELD_COPY_FALSE: int = 0x0
NVB1C0_QMDV01_07_DEPENDENT_QMD_FIELD_COPY_TRUE: int = 0x1
NVB1C0_QMDV01_07_INVALIDATE_TEXTURE_HEADER_CACHE_FALSE: int = 0x0
NVB1C0_QMDV01_07_INVALIDATE_TEXTURE_HEADER_CACHE_TRUE: int = 0x1
NVB1C0_QMDV01_07_INVALIDATE_TEXTURE_SAMPLER_CACHE_FALSE: int = 0x0
NVB1C0_QMDV01_07_INVALIDATE_TEXTURE_SAMPLER_CACHE_TRUE: int = 0x1
NVB1C0_QMDV01_07_INVALIDATE_TEXTURE_DATA_CACHE_FALSE: int = 0x0
NVB1C0_QMDV01_07_INVALIDATE_TEXTURE_DATA_CACHE_TRUE: int = 0x1
NVB1C0_QMDV01_07_INVALIDATE_SHADER_DATA_CACHE_FALSE: int = 0x0
NVB1C0_QMDV01_07_INVALIDATE_SHADER_DATA_CACHE_TRUE: int = 0x1
NVB1C0_QMDV01_07_INVALIDATE_INSTRUCTION_CACHE_FALSE: int = 0x0
NVB1C0_QMDV01_07_INVALIDATE_INSTRUCTION_CACHE_TRUE: int = 0x1
NVB1C0_QMDV01_07_INVALIDATE_SHADER_CONSTANT_CACHE_FALSE: int = 0x0
NVB1C0_QMDV01_07_INVALIDATE_SHADER_CONSTANT_CACHE_TRUE: int = 0x1
NVB1C0_QMDV01_07_RELEASE_MEMBAR_TYPE_FE_NONE: int = 0x0
NVB1C0_QMDV01_07_RELEASE_MEMBAR_TYPE_FE_SYSMEMBAR: int = 0x1
NVB1C0_QMDV01_07_CWD_REFERENCE_COUNT_INCR_ENABLE_FALSE: int = 0x0
NVB1C0_QMDV01_07_CWD_REFERENCE_COUNT_INCR_ENABLE_TRUE: int = 0x1
NVB1C0_QMDV01_07_CWD_MEMBAR_TYPE_L1_NONE: int = 0x0
NVB1C0_QMDV01_07_CWD_MEMBAR_TYPE_L1_SYSMEMBAR: int = 0x1
NVB1C0_QMDV01_07_CWD_MEMBAR_TYPE_L1_MEMBAR: int = 0x3
NVB1C0_QMDV01_07_SEQUENTIALLY_RUN_CTAS_FALSE: int = 0x0
NVB1C0_QMDV01_07_SEQUENTIALLY_RUN_CTAS_TRUE: int = 0x1
NVB1C0_QMDV01_07_CWD_REFERENCE_COUNT_DECR_ENABLE_FALSE: int = 0x0
NVB1C0_QMDV01_07_CWD_REFERENCE_COUNT_DECR_ENABLE_TRUE: int = 0x1
NVB1C0_QMDV01_07_THROTTLED_FALSE: int = 0x0
NVB1C0_QMDV01_07_THROTTLED_TRUE: int = 0x1
NVB1C0_QMDV01_07_FP32_NAN_BEHAVIOR_LEGACY: int = 0x0
NVB1C0_QMDV01_07_FP32_NAN_BEHAVIOR_FP64_COMPATIBLE: int = 0x1
NVB1C0_QMDV01_07_FP32_F2I_NAN_BEHAVIOR_PASS_ZERO: int = 0x0
NVB1C0_QMDV01_07_FP32_F2I_NAN_BEHAVIOR_PASS_INDEFINITE: int = 0x1
NVB1C0_QMDV01_07_API_VISIBLE_CALL_LIMIT__32: int = 0x0
NVB1C0_QMDV01_07_API_VISIBLE_CALL_LIMIT_NO_CHECK: int = 0x1
NVB1C0_QMDV01_07_SHARED_MEMORY_BANK_MAPPING_FOUR_BYTES_PER_BANK: int = 0x0
NVB1C0_QMDV01_07_SHARED_MEMORY_BANK_MAPPING_EIGHT_BYTES_PER_BANK: int = 0x1
NVB1C0_QMDV01_07_SAMPLER_INDEX_INDEPENDENTLY: int = 0x0
NVB1C0_QMDV01_07_SAMPLER_INDEX_VIA_HEADER_INDEX: int = 0x1
NVB1C0_QMDV01_07_FP32_NARROW_INSTRUCTION_KEEP_DENORMS: int = 0x0
NVB1C0_QMDV01_07_FP32_NARROW_INSTRUCTION_FLUSH_DENORMS: int = 0x1
NVB1C0_QMDV01_07_CONSTANT_BUFFER_VALID_FALSE: int = 0x0
NVB1C0_QMDV01_07_CONSTANT_BUFFER_VALID_TRUE: int = 0x1
NVB1C0_QMDV01_07_L1_CONFIGURATION_DIRECTLY_ADDRESSABLE_MEMORY_SIZE_16KB: int = 0x1
NVB1C0_QMDV01_07_L1_CONFIGURATION_DIRECTLY_ADDRESSABLE_MEMORY_SIZE_32KB: int = 0x2
NVB1C0_QMDV01_07_L1_CONFIGURATION_DIRECTLY_ADDRESSABLE_MEMORY_SIZE_48KB: int = 0x3
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_OP_RED_ADD: int = 0x0
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_OP_RED_MIN: int = 0x1
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_OP_RED_MAX: int = 0x2
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_OP_RED_INC: int = 0x3
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_OP_RED_DEC: int = 0x4
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_OP_RED_AND: int = 0x5
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_OP_RED_OR: int = 0x6
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_OP_RED_XOR: int = 0x7
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_FORMAT_UNSIGNED_32: int = 0x0
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_FORMAT_SIGNED_32: int = 0x1
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_ENABLE_FALSE: int = 0x0
NVB1C0_QMDV01_07_RELEASE0_REDUCTION_ENABLE_TRUE: int = 0x1
NVB1C0_QMDV01_07_RELEASE0_STRUCTURE_SIZE_FOUR_WORDS: int = 0x0
NVB1C0_QMDV01_07_RELEASE0_STRUCTURE_SIZE_ONE_WORD: int = 0x1
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_OP_RED_ADD: int = 0x0
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_OP_RED_MIN: int = 0x1
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_OP_RED_MAX: int = 0x2
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_OP_RED_INC: int = 0x3
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_OP_RED_DEC: int = 0x4
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_OP_RED_AND: int = 0x5
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_OP_RED_OR: int = 0x6
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_OP_RED_XOR: int = 0x7
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_FORMAT_UNSIGNED_32: int = 0x0
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_FORMAT_SIGNED_32: int = 0x1
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_ENABLE_FALSE: int = 0x0
NVB1C0_QMDV01_07_RELEASE1_REDUCTION_ENABLE_TRUE: int = 0x1
NVB1C0_QMDV01_07_RELEASE1_STRUCTURE_SIZE_FOUR_WORDS: int = 0x0
NVB1C0_QMDV01_07_RELEASE1_STRUCTURE_SIZE_ONE_WORD: int = 0x1
NVB1C0_QMDV01_07_CONSTANT_BUFFER_INVALIDATE_FALSE: int = 0x0
NVB1C0_QMDV01_07_CONSTANT_BUFFER_INVALIDATE_TRUE: int = 0x1
NVB1C0_QMDV01_07_HW_ONLY_SPAN_LIST_HEAD_INDEX_VALID_FALSE: int = 0x0
NVB1C0_QMDV01_07_HW_ONLY_SPAN_LIST_HEAD_INDEX_VALID_TRUE: int = 0x1




class qmdv0006(Structure):
    _fields_ = [
        ("qmd_reserved_v1_a", c_uint, 31),
        ("qmd_reserved_v1_b", c_uint, 1),
        ("qmd_reserved_v1_c", c_uint, 31),
        ("qmd_reserved_v1_d", c_uint, 1),
        ("qmd_reserved_v1_e", c_uint, 31),
        ("qmd_reserved_v1_f", c_uint, 1),
        ("qmd_reserved_v1_g", c_uint, 31),
        ("qmd_reserved_v1_h", c_uint, 1),
        ("qmd_reserved_a_a", c_uint, 32),
        ("qmd_reserved_v1_i", c_uint, 32),
        ("qmd_reserved_v1_j", c_uint, 5),
        ("qmd_reserved_a", c_uint, 3),
        ("qmd_reserved_v1_k", c_uint, 1),
        ("qmd_reserved_v1_l", c_uint, 1),
        ("semaphore_release_enable0", c_uint, 1),
        ("semaphore_release_enable1", c_uint, 1),
        ("qmd_reserved_b", c_uint, 4),
        ("qmd_reserved_v1_m", c_uint, 15),
        ("qmd_reserved_v1_n", c_uint, 1),
        ("qmd_reserved_v1_o", c_uint, 25),
        ("qmd_reserved_c", c_uint, 1),
        ("invalidate_texture_header_cache", c_uint, 1),
        ("invalidate_texture_sampler_cache", c_uint, 1),
        ("invalidate_texture_data_cache", c_uint, 1),
        ("invalidate_shader_data_cache", c_uint, 1),
        ("invalidate_instruction_cache", c_uint, 1),
        ("invalidate_shader_constant_cache", c_uint, 1),
        ("program_offset", c_uint, 32),
        ("qmd_reserved_v1_p", c_uint, 32),
        ("qmd_reserved_v1_q", c_uint, 8),
        ("qmd_reserved_d", c_uint, 8),
        ("qmd_reserved_v1_r", c_uint, 16),
        ("qmd_reserved_v1_s", c_uint, 6),
        ("qmd_reserved_e", c_uint, 8),
        ("release_membar_type", c_uint, 1),
        ("cwd_membar_type", c_uint, 2),
        ("qmd_reserved_v1_t", c_uint, 1),
        ("qmd_reserved_v1_u", c_uint, 1),
        ("throttled", c_uint, 1),
        ("qmd_reserved_e2_a", c_uint, 1),
        ("qmd_reserved_e2_b", c_uint, 1),
        ("api_visible_call_limit", c_uint, 1),
        ("shared_memory_bank_mapping", c_uint, 1),
        ("sampler_index", c_uint, 1),
        ("qmd_reserved_e3_a", c_uint, 1),
        ("cta_raster_width", c_uint, 32),
        ("cta_raster_height", c_uint, 16),
        ("cta_raster_depth", c_uint, 16),
        ("cta_raster_width_resume", c_uint, 32),
        ("cta_raster_height_resume", c_uint, 16),
        ("cta_raster_depth_resume", c_uint, 16),
        ("qmd_reserved_v1_v", c_uint, 24),
        ("qmd_reserved_f", c_uint, 7),
        ("qmd_reserved_v1_w", c_uint, 1),
        ("shared_memory_size", c_uint, 18),
        ("qmd_reserved_g", c_uint, 14),
        ("qmd_version", c_uint, 4),
        ("qmd_major_version", c_uint, 4),
        ("qmd_reserved_h", c_uint, 8),
        ("cta_thread_dimension0", c_uint, 16),
        ("cta_thread_dimension1", c_uint, 16),
        ("cta_thread_dimension2", c_uint, 16),
        ("constant_buffer_valid_0", c_uint, 1),
        ("constant_buffer_valid_1", c_uint, 1),
        ("constant_buffer_valid_2", c_uint, 1),
        ("constant_buffer_valid_3", c_uint, 1),
        ("constant_buffer_valid_4", c_uint, 1),
        ("constant_buffer_valid_5", c_uint, 1),
        ("constant_buffer_valid_6", c_uint, 1),
        ("constant_buffer_valid_7", c_uint, 1),
        ("qmd_reserved_i", c_uint, 21),
        ("l1_configuration", c_uint, 3),
        ("qmd_reserved_v1_x", c_uint, 32),
        ("qmd_reserved_v1_y", c_uint, 32),
        ("release0_address_lower", c_uint, 32),
        ("release0_address_upper", c_uint, 8),
        ("qmd_reserved_j", c_uint, 8),
        ("release0_reduction_op", c_uint, 3),
        ("qmd_reserved_k", c_uint, 1),
        ("release0_reduction_format", c_uint, 2),
        ("release0_reduction_enable", c_uint, 1),
        ("release0_structure_size", c_uint, 1),
        ("release0_payload", c_uint, 32),
        ("release1_address_lower", c_uint, 32),
        ("release1_address_upper", c_uint, 8),
        ("qmd_reserved_l", c_uint, 8),
        ("release1_reduction_op", c_uint, 3),
        ("qmd_reserved_m", c_uint, 1),
        ("release1_reduction_format", c_uint, 2),
        ("release1_reduction_enable", c_uint, 1),
        ("release1_structure_size", c_uint, 1),
        ("release1_payload", c_uint, 32),
        ("constant_buffer_addr_lower_0", c_uint, 32),
        ("constant_buffer_addr_upper_0", c_uint, 8),
        ("constant_buffer_reserved_addr_0", c_uint, 6),
        ("constant_buffer_invalidate_0", c_uint, 1),
        ("constant_buffer_size_0", c_uint, 17),
        ("constant_buffer_addr_lower_1", c_uint, 32),
        ("constant_buffer_addr_upper_1", c_uint, 8),
        ("constant_buffer_reserved_addr_1", c_uint, 6),
        ("constant_buffer_invalidate_1", c_uint, 1),
        ("constant_buffer_size_1", c_uint, 17),
        ("constant_buffer_addr_lower_2", c_uint, 32),
        ("constant_buffer_addr_upper_2", c_uint, 8),
        ("constant_buffer_reserved_addr_2", c_uint, 6),
        ("constant_buffer_invalidate_2", c_uint, 1),
        ("constant_buffer_size_2", c_uint, 17),
        ("constant_buffer_addr_lower_3", c_uint, 32),
        ("constant_buffer_addr_upper_3", c_uint, 8),
        ("constant_buffer_reserved_addr_3", c_uint, 6),
        ("constant_buffer_invalidate_3", c_uint, 1),
        ("constant_buffer_size_3", c_uint, 17),
        ("constant_buffer_addr_lower_4", c_uint, 32),
        ("constant_buffer_addr_upper_4", c_uint, 8),
        ("constant_buffer_reserved_addr_4", c_uint, 6),
        ("constant_buffer_invalidate_4", c_uint, 1),
        ("constant_buffer_size_4", c_uint, 17),
        ("constant_buffer_addr_lower_5", c_uint, 32),
        ("constant_buffer_addr_upper_5", c_uint, 8),
        ("constant_buffer_reserved_addr_5", c_uint, 6),
        ("constant_buffer_invalidate_5", c_uint, 1),
        ("constant_buffer_size_5", c_uint, 17),
        ("constant_buffer_addr_lower_6", c_uint, 32),
        ("constant_buffer_addr_upper_6", c_uint, 8),
        ("constant_buffer_reserved_addr_6", c_uint, 6),
        ("constant_buffer_invalidate_6", c_uint, 1),
        ("constant_buffer_size_6", c_uint, 17),
        ("constant_buffer_addr_lower_7", c_uint, 32),
        ("constant_buffer_addr_upper_7", c_uint, 8),
        ("constant_buffer_reserved_addr_7", c_uint, 6),
        ("constant_buffer_invalidate_7", c_uint, 1),
        ("constant_buffer_size_7", c_uint, 17),
        ("shader_local_memory_low_size", c_uint, 24),
        ("qmd_reserved_n", c_uint, 3),
        ("barrier_count", c_uint, 5),
        ("shader_local_memory_high_size", c_uint, 24),
        ("register_count", c_uint, 8),
        ("shader_local_memory_crs_size", c_uint, 24),
        ("sass_version", c_uint, 8),
        ("qmd_spare_a", c_uint, 32),
        ("qmd_spare_b", c_uint, 32),
        ("qmd_spare_c", c_uint, 32),
        ("qmd_spare_d", c_uint, 32),
        ("qmd_spare_e", c_uint, 32),
        ("qmd_spare_f", c_uint, 32),
        ("qmd_spare_g", c_uint, 32),
        ("qmd_spare_h", c_uint, 32),
        ("qmd_spare_i", c_uint, 32),
        ("qmd_spare_j", c_uint, 32),
        ("qmd_spare_k", c_uint, 32),
        ("qmd_spare_l", c_uint, 32),
        ("qmd_spare_m", c_uint, 32),
        ("qmd_spare_n", c_uint, 32),
        ("debug_id_upper", c_uint, 32),
        ("debug_id_lower", c_uint, 32),
    ]


class qmdv0107(Structure):
    _fields_ = [
        ("outer_put", c_uint, 31),
        ("outer_overflow", c_uint, 1),
        ("outer_get", c_uint, 31),
        ("outer_sticky_overflow", c_uint, 1),
        ("inner_get", c_uint, 31),
        ("inner_overflow", c_uint, 1),
        ("inner_put", c_uint, 31),
        ("inner_sticky_overflow", c_uint, 1),
        ("qmd_reserved_a_a", c_uint, 32),
        ("dependent_qmd_pointer", c_uint, 32),
        ("qmd_group_id", c_uint, 6),
        ("sm_global_caching_enable", c_uint, 1),
        ("run_cta_in_one_sm_partition", c_uint, 1),
        ("is_queue", c_uint, 1),
        ("add_to_head_of_qmd_group_linked_list", c_uint, 1),
        ("semaphore_release_enable0", c_uint, 1),
        ("semaphore_release_enable1", c_uint, 1),
        ("require_scheduling_pcas", c_uint, 1),
        ("dependent_qmd_schedule_enable", c_uint, 1),
        ("dependent_qmd_type", c_uint, 1),
        ("dependent_qmd_field_copy", c_uint, 1),
        ("qmd_reserved_b", c_uint, 16),
        ("circular_queue_size", c_uint, 25),
        ("qmd_reserved_c", c_uint, 1),
        ("invalidate_texture_header_cache", c_uint, 1),
        ("invalidate_texture_sampler_cache", c_uint, 1),
        ("invalidate_texture_data_cache", c_uint, 1),
        ("invalidate_shader_data_cache", c_uint, 1),
        ("invalidate_instruction_cache", c_uint, 1),
        ("invalidate_shader_constant_cache", c_uint, 1),
        ("program_offset", c_uint, 32),
        ("circular_queue_addr_lower", c_uint, 32),
        ("circular_queue_addr_upper", c_uint, 8),
        ("qmd_reserved_d", c_uint, 8),
        ("circular_queue_entry_size", c_uint, 16),
        ("cwd_reference_count_id", c_uint, 6),
        ("cwd_reference_count_delta_minus_one", c_uint, 8),
        ("release_membar_type", c_uint, 1),
        ("cwd_reference_count_incr_enable", c_uint, 1),
        ("cwd_membar_type", c_uint, 2),
        ("sequentially_run_ctas", c_uint, 1),
        ("cwd_reference_count_decr_enable", c_uint, 1),
        ("throttled", c_uint, 1),
        ("fp32_nan_behavior", c_uint, 1),
        ("fp32_f2i_nan_behavior", c_uint, 1),
        ("api_visible_call_limit", c_uint, 1),
        ("shared_memory_bank_mapping", c_uint, 1),
        ("sampler_index", c_uint, 1),
        ("fp32_narrow_instruction", c_uint, 1),
        ("cta_raster_width", c_uint, 32),
        ("cta_raster_height", c_uint, 16),
        ("cta_raster_depth", c_uint, 16),
        ("cta_raster_width_resume", c_uint, 32),
        ("cta_raster_height_resume", c_uint, 16),
        ("cta_raster_depth_resume", c_uint, 16),
        ("queue_entries_per_cta_minus_one", c_uint, 7),
        ("coalesce_waiting_period", c_uint, 8),
        ("shared_memory_size", c_uint, 18),
        ("qmd_reserved_g", c_uint, 14),
        ("qmd_version", c_uint, 4),
        ("qmd_major_version", c_uint, 4),
        ("qmd_reserved_h", c_uint, 8),
        ("cta_thread_dimension0", c_uint, 16),
        ("cta_thread_dimension1", c_uint, 16),
        ("cta_thread_dimension2", c_uint, 16),
        ("constant_buffer_valid_0", c_uint, 1),
        ("constant_buffer_valid_1", c_uint, 1),
        ("constant_buffer_valid_2", c_uint, 1),
        ("constant_buffer_valid_3", c_uint, 1),
        ("constant_buffer_valid_4", c_uint, 1),
        ("constant_buffer_valid_5", c_uint, 1),
        ("constant_buffer_valid_6", c_uint, 1),
        ("constant_buffer_valid_7", c_uint, 1),
        ("qmd_reserved_i", c_uint, 21),
        ("l1_configuration", c_uint, 3),
        ("sm_disable_mask_lower", c_uint, 32),
        ("sm_disable_mask_upper", c_uint, 32),
        ("release0_address_lower", c_uint, 32),
        ("release0_address_upper", c_uint, 8),
        ("qmd_reserved_j", c_uint, 8),
        ("release0_reduction_op", c_uint, 3),
        ("qmd_reserved_k", c_uint, 1),
        ("release0_reduction_format", c_uint, 2),
        ("release0_reduction_enable", c_uint, 1),
        ("release0_structure_size", c_uint, 1),
        ("release0_payload", c_uint, 32),
        ("release1_address_lower", c_uint, 32),
        ("release1_address_upper", c_uint, 8),
        ("qmd_reserved_l", c_uint, 8),
        ("release1_reduction_op", c_uint, 3),
        ("qmd_reserved_m", c_uint, 1),
        ("release1_reduction_format", c_uint, 2),
        ("release1_reduction_enable", c_uint, 1),
        ("release1_structure_size", c_uint, 1),
        ("release1_payload", c_uint, 32),
        ("constant_buffer_addr_lower_0", c_uint, 32),
        ("constant_buffer_addr_upper_0", c_uint, 8),
        ("constant_buffer_reserved_addr_0", c_uint, 6),
        ("constant_buffer_invalidate_0", c_uint, 1),
        ("constant_buffer_size_0", c_uint, 17),
        ("constant_buffer_addr_lower_1", c_uint, 32),
        ("constant_buffer_addr_upper_1", c_uint, 8),
        ("constant_buffer_reserved_addr_1", c_uint, 6),
        ("constant_buffer_invalidate_1", c_uint, 1),
        ("constant_buffer_size_1", c_uint, 17),
        ("constant_buffer_addr_lower_2", c_uint, 32),
        ("constant_buffer_addr_upper_2", c_uint, 8),
        ("constant_buffer_reserved_addr_2", c_uint, 6),
        ("constant_buffer_invalidate_2", c_uint, 1),
        ("constant_buffer_size_2", c_uint, 17),
        ("constant_buffer_addr_lower_3", c_uint, 32),
        ("constant_buffer_addr_upper_3", c_uint, 8),
        ("constant_buffer_reserved_addr_3", c_uint, 6),
        ("constant_buffer_invalidate_3", c_uint, 1),
        ("constant_buffer_size_3", c_uint, 17),
        ("constant_buffer_addr_lower_4", c_uint, 32),
        ("constant_buffer_addr_upper_4", c_uint, 8),
        ("constant_buffer_reserved_addr_4", c_uint, 6),
        ("constant_buffer_invalidate_4", c_uint, 1),
        ("constant_buffer_size_4", c_uint, 17),
        ("constant_buffer_addr_lower_5", c_uint, 32),
        ("constant_buffer_addr_upper_5", c_uint, 8),
        ("constant_buffer_reserved_addr_5", c_uint, 6),
        ("constant_buffer_invalidate_5", c_uint, 1),
        ("constant_buffer_size_5", c_uint, 17),
        ("constant_buffer_addr_lower_6", c_uint, 32),
        ("constant_buffer_addr_upper_6", c_uint, 8),
        ("constant_buffer_reserved_addr_6", c_uint, 6),
        ("constant_buffer_invalidate_6", c_uint, 1),
        ("constant_buffer_size_6", c_uint, 17),
        ("constant_buffer_addr_lower_7", c_uint, 32),
        ("constant_buffer_addr_upper_7", c_uint, 8),
        ("constant_buffer_reserved_addr_7", c_uint, 6),
        ("constant_buffer_invalidate_7", c_uint, 1),
        ("constant_buffer_size_7", c_uint, 17),
        ("shader_local_memory_low_size", c_uint, 24),
        ("qmd_reserved_n", c_uint, 3),
        ("barrier_count", c_uint, 5),
        ("shader_local_memory_high_size", c_uint, 24),
        ("register_count", c_uint, 8),
        ("shader_local_memory_crs_size", c_uint, 24),
        ("sass_version", c_uint, 8),
        ("hw_only_inner_get", c_uint, 31),
        ("hw_only_require_scheduling_pcas", c_uint, 1),
        ("hw_only_inner_put", c_uint, 31),
        ("hw_only_scg_type", c_uint, 1),
        ("hw_only_span_list_head_index", c_uint, 30),
        ("qmd_reserved_q", c_uint, 1),
        ("hw_only_span_list_head_index_valid", c_uint, 1),
        ("hw_only_sked_next_qmd_pointer", c_uint, 32),
        ("qmd_spare_e", c_uint, 32),
        ("qmd_spare_f", c_uint, 32),
        ("qmd_spare_g", c_uint, 32),
        ("qmd_spare_h", c_uint, 32),
        ("qmd_spare_i", c_uint, 32),
        ("qmd_spare_j", c_uint, 32),
        ("qmd_spare_k", c_uint, 32),
        ("qmd_spare_l", c_uint, 32),
        ("qmd_spare_m", c_uint, 32),
        ("qmd_spare_n", c_uint, 32),
        ("debug_id_upper", c_uint, 32),
        ("debug_id_lower", c_uint, 32),
    ]






